import { modelIndex } from './model-index';
export type OrganId = 'heart' | 'lungs' | 'brain';
export type ModelId = OrganId | 'body';
export interface Structure { id:string; title:string; latin?:string; sourceLabel:string; children:string[]; parent?:string; mesh:boolean; ontologyId?:string }
export const MODEL_DEFINITIONS = {
 heart:{id:'heart',title:'Corazón',latin:'Cor',system:'Sistema cardiovascular',code:'01',color:'#B46F6F',root:'VH_M_heart',meshCount:14,description:'Cámaras, válvulas, tabique y músculos papilares, en 14 piezas independientes.',sourceUrl:'https://github.com/hubmapconsortium/ccf-3d-reference-object-library/blob/main/VH_Male/v1.2/VH_M_Heart.glb'},
 lungs:{id:'lungs',title:'Pulmones',latin:'Pulmones',system:'Sistema respiratorio',code:'02',color:'#BE9EA3',root:'VH_M_respiratory_system',meshCount:58,description:'Lóbulos, segmentos broncopulmonares y árbol bronquial, en 58 piezas independientes.',sourceUrl:'https://github.com/hubmapconsortium/ccf-3d-reference-object-library/blob/main/VH_Male/v1.4/3d-vh-m-lung.glb'},
 brain:{id:'brain',title:'Encéfalo',latin:'Encephalon',system:'Sistema nervioso',code:'03',color:'#BF9C85',root:'Allen_brain',meshCount:283,description:'Hemisferios y estructuras corticales y profundas del modelo Allen, en 283 piezas independientes.',sourceUrl:'https://github.com/hubmapconsortium/ccf-3d-reference-object-library/blob/main/VH_Male/v1.2/Allen_M_Brain.glb'}
} as const;
const named:Record<string,[string,string?]>={
 VH_M_heart:['Corazón','Cor'],VH_M_heart_valve:['Válvulas cardíacas'],VH_M_mitral_valve:['Válvula mitral','Valva mitralis'],VH_M_tricuspid_valve:['Válvula tricúspide','Valva tricuspidalis'],VH_M_aortic_valve:['Válvula aórtica','Valva aortae'],VH_M_pulmonary_valve:['Válvula pulmonar','Valva trunci pulmonalis'],
 VH_M_papillary_muscle_of_heart:['Músculos papilares','Musculi papillares'],VH_M_papillary_muscle_of_heart_anterior:['Músculo papilar anterior'],VH_M_papillary_muscle_of_heart_anterolateral:['Músculo papilar anterolateral'],VH_M_papillary_muscle_of_heart_medial:['Músculo papilar septal'],VH_M_papillary_muscle_of_heart_posterior:['Músculo papilar posterior'],VH_M_papillary_muscle_of_heart_posteromedial:['Músculo papilar posteromedial'],
 VH_M_cardiac_chamber:['Cámaras y tabique'],VH_M_left_cardiac_atrium:['Aurícula izquierda','Atrium sinistrum'],VH_M_right_cardiac_atrium:['Aurícula derecha','Atrium dextrum'],VH_M_heart_right_ventricle:['Ventrículo derecho','Ventriculus dexter'],VH_M_heart_left_ventricle:['Ventrículo izquierdo','Ventriculus sinister'],VH_M_interventricular_septum:['Tabique interventricular','Septum interventriculare'],
 VH_M_respiratory_system:['Sistema respiratorio'],VH_M_lungs:['Pulmones','Pulmones'],VH_M_lungs_L:['Pulmón izquierdo','Pulmo sinister'],VH_M_lungs_R:['Pulmón derecho','Pulmo dexter'],
 VH_M_lungs_L_upper_lobe:['Lóbulo superior izquierdo','Lobus superior pulmonis sinistri'],VH_M_lungs_L_lower_lobe:['Lóbulo inferior izquierdo','Lobus inferior pulmonis sinistri'],VH_M_lungs_R_upper_lobe:['Lóbulo superior derecho','Lobus superior pulmonis dextri'],VH_M_lungs_R_middle_lobe:['Lóbulo medio derecho','Lobus medius pulmonis dextri'],VH_M_lungs_R_lower_lobe:['Lóbulo inferior derecho','Lobus inferior pulmonis dextri'],
 VH_M_right_posterior_basal:['Bronquio segmentario basal posterior derecho'],VH_M_bronchus:['Bronquio derecho'],VH_M_tracheobronchial_tree:['Árbol bronquial'],VH_M_bronchi:['Bronquios','Bronchi'],VH_M_bronchi_L:['Bronquios izquierdos'],VH_M_bronchi_R:['Bronquios derechos'],VH_M_left_bronchial_cartilage:['Cartílago bronquial izquierdo'],VH_M_right_bronchial_cartilage:['Cartílago bronquial derecho'],VH_M_lobar_bronchus_L:['Bronquios lobares izquierdos'],VH_M_lobar_bronchi_R:['Bronquios lobares derechos'],VH_M_tertiary_bronchi_L:['Bronquios segmentarios izquierdos'],VH_M_tertiary_bronchi_R:['Bronquios segmentarios derechos'],
 Allen_brain:['Encéfalo','Encephalon'],Allen_brain_Hemisphere_L:['Hemisferio izquierdo','Hemispherium cerebri sinistrum'],Allen_brain_Hemisphere_R:['Hemisferio derecho','Hemispherium cerebri dextrum'],VH_M_optic_chiasm:['Quiasma óptico','Chiasma opticum']
};
const terms:Record<string,string>={
'frontal agranular insular cortex area Fl':'corteza insular agranular frontal, área Fl','temporal agranular insular cortex area Tl':'corteza insular agranular temporal, área Tl','inferior olive':'oliva inferior','middle cerebellar peduncle':'pedúnculo cerebeloso medio','midline nuclear complex':'complejo nuclear de la línea media','lateral olfactory gyrus':'giro olfatorio lateral','parietal operculum':'opérculo parietal','optic radiation':'radiación óptica','posteroventral putamen':'putamen posteroventral','atrium of lateral ventricle':'atrio del ventrículo lateral','paracingulate gyrus':'giro paracingulado','rostral gyrus':'giro rostral','frontomarginal gyrus':'giro frontomarginal','frontal pole':'polo frontal','inferior cerebellar peduncle':'pedúnculo cerebeloso inferior','perirhinal gyrus rostral part of FuGt':'giro perirrinal, porción rostral','red nucleus':'núcleo rojo','hypothalamus':'hipotálamo','subthalamic nucleus':'núcleo subtalámico','mammillary region of HTH':'región mamilar del hipotálamo','midbrain tegmentum':'tegmento del mesencéfalo',
 'lateral hemisphere of cerebellum':'hemisferio lateral del cerebelo','white matter of forebrain':'sustancia blanca del prosencéfalo','white matter of hindbrain':'sustancia blanca del rombencéfalo','cerebellar deep nuclei':'núcleos profundos del cerebelo','basilar part of pons':'porción basilar del puente','pontine tegmentum':'tegmento pontino','pyramidal part of medulla oblongata':'porción piramidal del bulbo raquídeo','tegmentum of medulla oblongata':'tegmento del bulbo raquídeo','central canal of medulla oblongata':'conducto central del bulbo raquídeo','cerebral peduncle crus cerebri':'pedúnculo cerebral','superior cerebellar peduncle brachium conjunctivum':'pedúnculo cerebeloso superior','cerebellar vermis':'vermis del cerebelo','paravermis of cerebellum':'paravermis del cerebelo',
 'olfactory bulb':'bulbo olfatorio','anterior olfactory nucleus':'núcleo olfatorio anterior','piriform region':'región piriforme','head of caudate':'cabeza del caudado','body of caudate':'cuerpo del caudado','tail of caudate':'cola del caudado','nucleus accumbens':'núcleo accumbens','external segment of globus pallidus':'segmento externo del globo pálido','internal segment of globus pallidus':'segmento interno del globo pálido','claustrum':'claustro','basal forebrain':'prosencéfalo basal','septal nuclei':'núcleos septales','amygdaloid complex':'complejo amigdalino','anterior amygdaloid area':'área amigdalina anterior','central nuclear group':'grupo nuclear central','basolateral nucleus basal nucleus':'núcleo basolateral','basomedial nucleus accessory basal nucleus':'núcleo basomedial','bed nucleus of stria terminalis':'núcleo del lecho de la estría terminal','amygdalohippocampal area':'área amigdalo-hipocampal',
 'anterior nuclear complex of thalamus':'complejo nuclear anterior del tálamo','lateral dorsal nucleus of thalamus':'núcleo dorsal lateral del tálamo','mediodorsal nucleus of thalamus':'núcleo mediodorsal del tálamo','reuniens nucleus medioventral nucleus of thalamus':'núcleo reuniens del tálamo','lateral posterior nucleus of thalamus':'núcleo lateral posterior del tálamo','pulvinar of thalamus':'pulvinar del tálamo','ventral anterior nucleus of thalamus':'núcleo ventral anterior del tálamo','ventral lateral nucleus of thalamus':'núcleo ventral lateral del tálamo','centromedian nucleus of thalamus':'núcleo centromediano del tálamo','parafascicular nucleus of thalamus':'núcleo parafascicular del tálamo','ventral posterior lateral nucleus':'núcleo ventral posterolateral','ventral posterior medial nucleus':'núcleo ventral posteromedial','dorsal lateral geniculate nucleus':'núcleo geniculado lateral dorsal','medial geniculate nuclei':'núcleos geniculados mediales','habenular nuclei':'núcleos habenulares','pineal body':'cuerpo pineal','zona incerta':'zona incierta','thalamus':'tálamo',
 'supraoptic region of HTH':'región supraóptica del hipotálamo','preoptic region of HTH':'región preóptica del hipotálamo','tuberal region of HTH':'región tuberal del hipotálamo','anterior commissure':'comisura anterior','corpus callosum':'cuerpo calloso','fornix':'fórnix','mammillothalamic tract':'tracto mamilotalámico','optic tract':'tracto óptico','anterior horn of lateral ventricle':'asta anterior del ventrículo lateral','body of lateral ventricle':'cuerpo del ventrículo lateral','posterior horn of lateral ventricle':'asta posterior del ventrículo lateral','inferior horn of lateral ventricle':'asta inferior del ventrículo lateral','third ventricle':'tercer ventrículo','fourth ventricle':'cuarto ventrículo','olfactory tract':'tracto olfatorio',
 'precentral gyrus':'giro precentral','postcentral gyrus':'giro poscentral','superior frontal gyrus':'giro frontal superior','middle frontal gyrus':'giro frontal medio','inferior frontal gyrus triangular part':'giro frontal inferior, porción triangular','inferior frontal gyrus opercular part':'giro frontal inferior, porción opercular','gyrus rectus straight gyrus':'giro recto','medial orbital gyrus':'giro orbitario medial','anterior intermediate orbital gyrus':'giro orbitario intermedio anterior','posterior intermediate orbital gyrus':'giro orbitario intermedio posterior','lateral orbital gyrus':'giro orbitario lateral','paracentral lobule rostral part':'lobulillo paracentral, porción rostral','paracentral lobule caudal part':'lobulillo paracentral, porción caudal','frontal operculum':'opérculo frontal','supraparietal lobule':'lobulillo parietal superior','supramarginal gyrus':'giro supramarginal','angular gyrus':'giro angular','precuneus':'precúneo','superior temporal gyrus':'giro temporal superior','middle temporal gyrus':'giro temporal medio','inferior temporal gyrus':'giro temporal inferior','occipitotemporal fusiform gyrus temporal part':'giro fusiforme, porción temporal','transverse temporal gyrus Heschls gyrus':'giro temporal transverso','planum temporale':'plano temporal','temporal pole':'polo temporal','planum polare':'plano polar','occipital pole':'polo occipital','cuneus':'cuña','lingual gyrus medial occipitotemporal gyrus':'giro lingual','lateral occipitotemporal fusiform gyrus occipital part':'giro fusiforme, porción occipital','inferior occipital gyrus':'giro occipital inferior','superior occipital gyrus':'giro occipital superior','cingulate gyrus rostral anterior part':'giro del cíngulo, porción anterior','cingulate gyrus caudal posterior part':'giro del cíngulo, porción posterior','ingulo parahippocampal isthmus':'istmo del cíngulo','subcallosal gyrus parolfactory gyrus':'giro subcalloso','anterior parahippocampal gyrus':'giro parahipocampal anterior','posterior parahippocampal gyrus':'giro parahipocampal posterior','gyrus ambiens':'giro ambiente','head of hippocampus':'cabeza del hipocampo','body of hippocampus':'cuerpo del hipocampo','tail of hippocampus':'cola del hipocampo','long insular gyri':'giros largos de la ínsula','short insular gyri':'giros cortos de la ínsula','limen insula':'umbral de la ínsula','pretectal region':'región pretectal','substantia nigra':'sustancia negra','superior colliculus':'colículo superior','inferior colliculus':'colículo inferior','cerebral aqueduct':'acueducto cerebral',
 'bronchopulmonary segment':'segmento broncopulmonar','bronchial cartilage':'cartílago bronquial','cartilage of the lobar bronchus':'cartílago del bronquio lobar','cartilage of the tertiary bronchus':'cartílago del bronquio segmentario','lingula':'língula','bronchus':'bronquio','hilum':'hilio','posetrior':'posterior','anterior cortical nucleus':'núcleo cortical anterior','posterior cortical nucleus':'núcleo cortical posterior','lateral nucleus':'núcleo lateral','medial nucleus':'núcleo medial'
};
function sourceToSpanish(id:string) {
 const suffix=/_L$/.test(id)?' · izquierdo':/_R$/.test(id)?' · derecho':'';
 let s=id.replace(/^(VH_M_|Allen_)/,'').replace(/_[LR]$/,'').replaceAll('_',' ');
 s=s.replace(/^left /,'').replace(/^right /,'');
 const lateral=/_left_/.test(id)?' · izquierdo':/_right_/.test(id)?' · derecho':suffix;
 if(terms[s])s=terms[s];else if(s.endsWith('bronchopulmonary segment'))s='segmento broncopulmonar '+s.replace('bronchopulmonary segment','').trim().replace('lingula ','lingular ').replace('posetrior','posterior');else if(s.endsWith('bronchus'))s='bronquio '+s.replace('bronchus','').trim().replace('lingula ','lingular ').replace('intermediate','intermedio').replace('lower','inferior');else {for(const [from,to] of Object.entries(terms))s=s.replaceAll(from,to);s=s.replaceAll('upper','superior').replaceAll('lower','inferior').replaceAll('middle','medio').replaceAll('intermediate','intermedio')}
 return s.charAt(0).toUpperCase()+s.slice(1)+lateral;
}
export const STRUCTURES=Object.fromEntries((['heart','lungs','brain'] as OrganId[]).map(organ=>{
 const raw=modelIndex[organ].nodes;const parents:Record<string,string>={};raw.forEach(n=>n.children.forEach(c=>{parents[c]=n.id}));
 const nodes:Structure[]=raw.map(n=>({id:n.id,title:named[n.id]?.[0]||sourceToSpanish(n.id),latin:named[n.id]?.[1],sourceLabel:n.label&&n.label!=='-'?n.label:n.id.replace(/^(VH_M_|Allen_)/,'').replaceAll('_',' '),children:[...n.children],parent:parents[n.id],mesh:n.mesh,ontologyId:n.ontologyId&&n.ontologyId!=='-'?n.ontologyId:undefined}));
 return [organ,nodes];
})) as Record<OrganId,Structure[]>;
const descendantCache=new Map<string,string[]>();
export function descendants(organ:OrganId,id:string){const cacheKey=organ+'/'+id;const cached=descendantCache.get(cacheKey);if(cached)return cached;const byId=new Map(STRUCTURES[organ].map(n=>[n.id,n]));const out:string[]=[];const visit=(key:string)=>{out.push(key);byId.get(key)?.children.forEach(visit)};visit(id);descendantCache.set(cacheKey,out);return out}
export function selectionFromScene(organ:OrganId,id:string|null){return id&&STRUCTURES[organ].some(n=>n.id===id)?id:null}
export const SOURCE_CREDIT='HRA / HuBMAP · CC BY 4.0';

