export type LessonKind = 'procedure' | 'first-aid';
export type LessonStep = { title: string; text: string };
export type Equipment = { id: string; name: string; purpose: string };
export type Lesson = { slug: string; kind: LessonKind; title: string; description: string; tag: string; icon: string; minutes: string; scene?: 'rcp' | 'pressure'; preparation?: boolean; steps: LessonStep[]; note: string; equipment: Equipment[]; sources: {title:string;url:string;date?:string}[] };
export const reviewDate = '14 de septiembre de 2026';
export const lessonHref = (lesson: Pick<Lesson, 'kind' | 'slug'>) => `/${lesson.kind === 'procedure' ? 'procedimientos' : 'primeros-auxilios'}/${lesson.slug}`;
const rc = (slug: string, title: string) => ({ title: `American Red Cross · ${title}`, url: `https://www.redcross.org/take-a-class/resources/learn-first-aid/${slug}` });
export const lessons: Lesson[] = [
{slug:'presion-arterial',kind:'procedure',title:'Medición de presión arterial',description:'Explora la postura y una medición de brazo.',tag:'Constantes vitales',icon:'pressure',minutes:'6 min',scene:'pressure',steps:[
{title:'Elige el equipo',text:'Usa un tensiómetro automático validado de brazo y un manguito del tamaño adecuado.'},
{title:'Prepara la medición',text:'Evita tabaco, cafeína y ejercicio los 30 minutos previos. Vacía la vejiga.'},
{title:'Descansa antes de empezar',text:'Permanece sentado al menos 5 minutos, en calma y sin hablar.'},
{title:'Ajusta la postura',text:'Apoya la espalda y los pies; mantén las piernas descruzadas y el brazo apoyado a la altura del corazón.'},
{title:'Coloca el manguito',text:'Colócalo sobre piel desnuda, por encima del pliegue del codo. Sigue las instrucciones del equipo.'},
{title:'Lee y registra',text:'Toma dos lecturas separadas por un minuto. Registra ambas para compartirlas con un profesional.'}],
note:'Datos del monitor ficticios. Una lectura aislada no diagnostica hipertensión. Si la sistólica supera 180 o la diastólica 120, repite tras al menos un minuto si no hay síntomas; si persiste, contacta inmediatamente con un profesional. Con dolor torácico, falta de aire, debilidad o alteraciones visuales o del habla, llama a emergencias sin esperar.',
equipment:[{id:'monitor',name:'Tensiómetro de brazo',purpose:'Muestra lecturas en mmHg. Valores ficticios en esta escena.'},{id:'manguito',name:'Manguito',purpose:'Compatible con el equipo y el tamaño del brazo.'},{id:'mesa',name:'Superficie de apoyo',purpose:'Apoyo estable para el brazo.'}],sources:[{title:'American Heart Association · Medición domiciliaria',url:'https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings/monitoring-your-blood-pressure-at-home',date:'Revisión: 14 agosto 2025'}]},
{slug:'signos-vitales',kind:'procedure',title:'Registro de signos vitales',description:'Conoce los instrumentos utilizados para observar constantes vitales.',tag:'Constantes vitales',icon:'pulse',minutes:'Ficha de equipo',preparation:true,steps:[],note:'El recorrido práctico y la escena 3D están en preparación. Esta ficha identifica material; no enseña un procedimiento de medición ni interpretación clínica.',equipment:[{id:'termometro',name:'Termómetro',purpose:'Instrumento de medición de temperatura.'},{id:'tensiometro',name:'Tensiómetro',purpose:'Instrumento de medición de presión arterial.'},{id:'reloj',name:'Reloj o cronómetro',purpose:'Referencia temporal para un registro.'}],sources:[]},
{slug:'vendaje',kind:'procedure',title:'Material para vendajes',description:'Identifica gasas, apósitos y vendas antes de la práctica.',tag:'Cuidados básicos',icon:'bandage',minutes:'Ficha de equipo',preparation:true,steps:[],note:'El recorrido práctico y la escena 3D están en preparación. La elección y aplicación de un vendaje dependen de la lesión y de la formación recibida.',equipment:[{id:'gasas',name:'Gasas estériles',purpose:'Material de cobertura de heridas.'},{id:'venda',name:'Venda en rollo',purpose:'Material para sujetar apósitos.'},{id:'guantes',name:'Guantes sin látex',purpose:'Barrera de protección personal.'}],sources:[{title:'American Red Cross · Botiquín',url:'https://www.redcross.org/get-help/how-to-prepare-for-emergencies/anatomy-of-a-first-aid-kit.html'}]},
{slug:'inmovilizacion',kind:'procedure',title:'Material de inmovilización',description:'Familiarízate con material de soporte para una práctica supervisada.',tag:'Traumatología',icon:'bone',minutes:'Ficha de equipo',preparation:true,steps:[],note:'El recorrido práctico y la escena 3D están en preparación. No recolocar ni enderezar una lesión. Las técnicas de inmovilización requieren formación práctica.',equipment:[{id:'triangular',name:'Venda triangular',purpose:'Material de soporte presente en botiquines.'},{id:'manta',name:'Manta',purpose:'Material para abrigo y confort mientras llega ayuda.'},{id:'guantes',name:'Guantes sin látex',purpose:'Barrera de protección personal.'}],sources:[rc('fractures','Fracturas'),{title:'American Red Cross · Botiquín',url:'https://www.redcross.org/get-help/how-to-prepare-for-emergencies/anatomy-of-a-first-aid-kit.html'}]},
{slug:'rcp',kind:'first-aid',title:'Reanimación cardiopulmonar',description:'Reconoce una posible parada y recorre la secuencia de RCP en adultos.',tag:'Soporte vital',icon:'heart',minutes:'7 min',scene:'rcp',steps:[
{title:'Comprueba la seguridad',text:'Acércate solo si el entorno es seguro.'},
{title:'Reconoce la parada',text:'Si no responde y no respira normalmente, presume parada. Los jadeos aislados no son respiración normal.'},
{title:'Activa la ayuda',text:'Llama a emergencias en altavoz y pide que traigan un DEA.'},
{title:'Coloca las manos',text:'Con la persona boca arriba, coloca ambas manos en el centro del pecho y mantén los brazos rectos.'},
{title:'Inicia compresiones',text:'Comprime a 100–120/min y 5–6 cm; permite la recuperación del pecho. Con formación, alterna 30 compresiones y 2 ventilaciones; si no, continúa solo con compresiones.'},
{title:'Utiliza el DEA',text:'Enciéndelo y sigue sus indicaciones. Nadie toca a la persona durante análisis o descarga. Reanuda las compresiones cuando indique.'}],note:'Adultos. No busques el pulso si no tienes formación sanitaria. La animación muestra una técnica esquemática: 110 compresiones/min a velocidad 1×; no mide fuerza ni profundidad reales. Continúa según el operador de emergencias.',equipment:[{id:'dea',name:'DEA',purpose:'Desfibrilador externo automático. Sigue sus mensajes de voz; analiza el ritmo e indica si procede una descarga.'},{id:'telefono',name:'Teléfono',purpose:'Permite activar emergencias y recibir instrucciones en altavoz.'}],sources:[{title:'American Heart Association · Soporte vital básico adulto',url:'https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines/adult-basic-life-support',date:'Guías 2025'}]},
{slug:'atragantamiento',kind:'first-aid',title:'Atragantamiento',description:'Distingue una tos eficaz de una obstrucción grave en un adulto.',tag:'Vía aérea',icon:'air',minutes:'5 min',steps:[{title:'Observa la tos',text:'Si puede hablar y toser con fuerza, anímale a toser y observa.'},{title:'Reconoce la gravedad',text:'Si no puede hablar, respirar o toser eficazmente, activa emergencias.'},{title:'Da golpes en la espalda',text:'Inclínalo hacia delante y administra 5 golpes entre los omóplatos.'},{title:'Alterna compresiones',text:'Si persiste, administra 5 compresiones abdominales hacia dentro y arriba. Alterna ambos grupos hasta expulsar el objeto o perder la respuesta.'},{title:'Si deja de responder',text:'Bájalo con cuidado e inicia RCP. Antes de ventilar, retira únicamente un objeto claramente visible en la boca.'}],note:'En embarazo avanzado o si no puedes rodear el abdomen, sustituye las abdominales por 5 compresiones torácicas. Nunca hagas un barrido ciego de la boca. Este módulo no se aplica a lactantes.',equipment:[{id:'telefono',name:'Teléfono',purpose:'Permite activar emergencias y seguir al operador.'}],sources:[{title:'American Heart Association · Obstrucción por cuerpo extraño',url:'https://cpr.heart.org/-/media/CPR-Files/CPR-Guidelines-Files/2025-Algorithms/Algorithm-BLS-Adult-FBAO-250630.pdf?sc_lang=en',date:'Algoritmo 2025'}]},
{slug:'hemorragias',kind:'first-aid',title:'Hemorragias',description:'Prioriza la ayuda y la presión directa ante una hemorragia externa grave.',tag:'Control del sangrado',icon:'drop',minutes:'5 min',steps:[{title:'Protege el entorno',text:'Comprueba la seguridad y utiliza guantes si están disponibles.'},{title:'Pide ayuda',text:'Activa emergencias si el sangrado es abundante o continuo.'},{title:'Aplica presión directa',text:'Localiza la herida, coloca una gasa o apósito y aplica presión firme y constante.'},{title:'Mantén la presión',text:'No levantes repetidamente el apósito. Un torniquete comercial para sangrado de extremidad que amenaza la vida y el empaquetamiento requieren formación.'},{title:'Acompaña y vigila',text:'Observa la respiración y la respuesta, evita que se enfríe y permanece con la persona.'}],note:'No retires un objeto incrustado: presiona alrededor. Esta ficha no sustituye la práctica de control de hemorragias ni enseña a fabricar un torniquete.',equipment:[{id:'guantes',name:'Guantes',purpose:'Barrera de protección.'},{id:'aposito',name:'Gasa o apósito',purpose:'Material para aplicar presión sobre la herida.'}],sources:[rc('bleeding-life-threatening-external','Hemorragia externa grave')]},
{slug:'quemaduras',kind:'first-aid',title:'Quemaduras',description:'Recorre el cuidado inicial de una quemadura térmica.',tag:'Lesiones de piel',icon:'fire',minutes:'5 min',steps:[{title:'Retira la fuente de calor',text:'Interrumpe el contacto con el calor sin exponerte al peligro.'},{title:'Enfría la zona',text:'Usa agua corriente fresca durante 20 minutos, lo antes posible.'},{title:'Retira objetos próximos',text:'Quita anillos y ropa próxima, excepto lo que esté adherido a la piel.'},{title:'Cubre sin apretar',text:'Después de enfriar, utiliza un apósito limpio no adherente o una lámina de film encima, sin envolver.'},{title:'Valora la urgencia',text:'Busca atención urgente si es extensa, profunda, afecta cara o genitales, o proviene de electricidad o sustancias químicas.'}],note:'No uses hielo, mantequilla ni cremas, ni rompas ampollas. Evita enfriar todo el cuerpo. Este recorrido de quemaduras térmicas no es un procedimiento completo para quemaduras químicas o eléctricas.',equipment:[{id:'agua',name:'Agua corriente fresca',purpose:'Medio para enfriar una quemadura térmica.'},{id:'aposito',name:'Apósito no adherente',purpose:'Cobertura limpia que no se pega a la zona.'}],sources:[{title:'NHS · Quemaduras',url:'https://www.nhs.uk/conditions/burns-and-scalds/',date:'Revisión: 31 marzo 2026'},rc('burns','Quemaduras')]},
{slug:'fracturas',kind:'first-aid',title:'Fracturas',description:'Reconoce una posible fractura y evita agravar la lesión.',tag:'Traumatología',icon:'bone',minutes:'5 min',steps:[{title:'Reconoce la lesión',text:'Considera una fractura ante dolor, hinchazón, deformidad o dificultad para mover.'},{title:'Mantén el reposo',text:'Deja la zona en la posición encontrada, sin probar el movimiento.'},{title:'Activa emergencias',text:'Pide ayuda urgente ante lesiones de cabeza, cuello, espalda, pelvis o muslo, herida abierta, falta de sensibilidad o lesión grave.'},{title:'Cuida la zona',text:'Con piel cerrada, aplica frío envuelto en una tela hasta 20 minutos. Si sangra, controla la hemorragia sin empujar huesos expuestos.'},{title:'Vigila hasta recibir ayuda',text:'Observa color, temperatura y sensibilidad por debajo de la lesión y solicita valoración sanitaria.'}],note:'No endereces ni recoloques. Poder mover una extremidad no descarta fractura. Las técnicas de inmovilización requieren formación.',equipment:[{id:'frio',name:'Compresa fría y tela',purpose:'La tela separa la compresa de la piel.'},{id:'guantes',name:'Guantes',purpose:'Barrera de protección ante heridas.'}],sources:[rc('fractures','Fracturas')]},
{slug:'desmayos',kind:'first-aid',title:'Desmayos',description:'Comprueba la respiración y reconoce las señales de alarma.',tag:'Pérdida de respuesta',icon:'person',minutes:'4 min',steps:[{title:'Evita una caída',text:'Si siente que va a desmayarse, ayúdale a tumbarse.'},{title:'Comprueba la respuesta',text:'Comprueba si responde y si respira normalmente.'},{title:'Facilita el reposo',text:'Si respira normalmente y no hay lesión que lo impida, colócalo boca arriba y eleva las piernas. En embarazo avanzado, de lado.'},{title:'Observa la recuperación',text:'Vigila y no lo incorpores bruscamente.'},{title:'Reconoce la alarma',text:'Activa emergencias si no despierta en un minuto, no se recupera del todo, tiene dolor torácico, dificultad para hablar o moverse, lesión grave, o se desmayó durante ejercicio o estando tumbado.'}],note:'Si no respira normalmente, no esperes un minuto: activa emergencias e inicia RCP. Un desmayo necesita valoración de su causa.',equipment:[{id:'telefono',name:'Teléfono',purpose:'Permite pedir ayuda y recibir instrucciones.'}],sources:[{title:'NHS · Desmayos',url:'https://www.nhs.uk/symptoms/fainting/',date:'Revisión: 17 agosto 2026'}]},
{slug:'convulsiones',kind:'first-aid',title:'Convulsiones',description:'Protege a la persona, cronometra la crisis y acompaña la recuperación.',tag:'Emergencias neurológicas',icon:'brain',minutes:'5 min',steps:[{title:'Despeja el espacio',text:'Retira objetos peligrosos; mueve a la persona solo si el lugar es peligroso.'},{title:'Protege la cabeza',text:'Usa algo blando y afloja prendas apretadas del cuello.'},{title:'Cronometra',text:'Anota el inicio. No sujetes sus movimientos ni introduzcas nada en la boca.'},{title:'Comprueba la respiración',text:'Cuando acaben los movimientos, comprueba si respira normalmente. Si respira, colócala de lado y acompáñala; si no, inicia RCP.'},{title:'Activa emergencias cuando corresponda',text:'Primera crisis, más de 5 minutos o más de su duración habitual, crisis repetidas sin recuperación, lesión grave o dificultad respiratoria.'}],note:'No des comida, bebida ni medicación oral durante la crisis. Un plan de medicación de rescate solo debe seguirlo quien conoce el plan y está formado.',equipment:[{id:'reloj',name:'Reloj o cronómetro',purpose:'Ayuda a informar la duración de la crisis.'},{id:'proteccion',name:'Protección blanda',purpose:'Puede amortiguar el contacto de la cabeza con el suelo.'}],sources:[{title:'NHS · Convulsiones',url:'https://www.nhs.uk/symptoms/what-to-do-if-someone-has-a-seizure-fit/',date:'Revisión: 19 diciembre 2023'},rc('seizures','Convulsiones')]},
{slug:'botiquin',kind:'first-aid',title:'Botiquín de primeros auxilios',description:'Organiza material esencial y mantenlo listo para cuando haga falta.',tag:'Preparación',icon:'kit',minutes:'4 min',steps:[{title:'Localiza el botiquín',text:'Elige un lugar accesible y conocido. Localiza también el del trabajo.'},{title:'Reúne el material básico',text:'Guantes sin látex, gasas y compresas estériles, apósitos adhesivos, cinta y vendas.'},{title:'Añade material de apoyo',text:'Manta térmica, barrera para ventilaciones, compresa fría y termómetro sin mercurio.'},{title:'Personaliza',text:'Incluye instrucciones de primeros auxilios, contactos y necesidades personales indicadas por profesionales.'},{title:'Revisa y repón',text:'Comprueba el contenido periódicamente; repón lo utilizado y retira lo caducado.'}],note:'Adapta el contenido a la actividad y a tu formación. Disponer de material no sustituye aprender a utilizarlo.',equipment:[{id:'guantes',name:'Guantes sin látex',purpose:'Protección personal.'},{id:'gasas',name:'Gasas y apósitos',purpose:'Material para heridas.'},{id:'manta',name:'Manta térmica',purpose:'Ayuda a mantener el abrigo.'}],sources:[{title:'American Red Cross · Preparar un botiquín',url:'https://www.redcross.org/get-help/how-to-prepare-for-emergencies/anatomy-of-a-first-aid-kit.html'}]}
];
