#!/usr/bin/env python3
"""Reproduce Phase 3B's metadata-only decision before any OBJ extraction.

Reads the preserved six BP3D metadata tables and pinned ZIP central directory.
--fetch refreshes ONLY those text tables and directory with exact hash checks.
No OBJ is extracted, parsed, converted, or generated by this script.
"""
from __future__ import annotations
import argparse
import collections
import csv
import hashlib
import io
import json
import re
import struct
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASE = 'https://dbarchive.biosciencedbc.jp/data/bodyparts3d/20130619/'
CACHE = ROOT / '.cache/bodyparts3d-4.0/metadata'
SOURCE = ROOT / 'research/anatomy/torso-metadata.zip'
OUTPUT = ROOT / 'research/anatomy/torso-selection.json'
DOC = ROOT / 'docs/phase3b-audit.md'
TABLES = {
    'isa_parts_list_e.txt': 'ab7796deedd49205e77f3609a1cb8c53e2bbee14ecb5c9a6ca05227469780513',
    'isa_element_parts.txt': 'a3de74423f943b0d724ae8f59b3a817f87c423a544f8db98113b1980817cbeaf',
    'isa_inclusion_relation_list.txt': '26e7d818e03a8c909fe09c561f38d0d513423c87681f9450a803bc38f5b07564',
    'partof_parts_list_e.txt': '9224080557053e6f1322f1e13ab27f0ecde0db19bb3b505f0631afad230eeebd',
    'partof_element_parts.txt': '3f5f6df1028eb122b30de77c711597b6bb8e5541658e5985859fd228adbf88ea',
    'partof_inclusion_relation_list.txt': '1b40738270931e3c1d955ce34e0fce0d8d10d8c5ad543463e40b4b4c0243007c',
}
CD_NAME = 'isa_BP3D_4.0_obj_99.central-directory.bin'
CD_OFFSET, CD_BYTES, ARCHIVE_BYTES = 142733851, 170025, 142903898
CD_SHA = 'edde15c7c5f34b2b9743935fb3c1873cce3a9789164427ddf8343c879bcde96b'
ARCHIVE_URL = BASE + 'isa_BP3D_4.0_obj_99.zip'

# Explicit source identities, not a heuristic import of a whole branch.
# family, label, region, component, right FMA, left FMA, right FJ
PAIRS = [
    ('pectoralismajor', 'Pectoral mayor', 'thorax-anterior', 'clavicular', 'FMA34690', 'FMA34691', 'FJ1447'),
    ('pectoralismajor', 'Pectoral mayor', 'thorax-anterior', 'sternocostal', 'FMA79979', 'FMA79980', 'FJ1464'),
    ('pectoralismajor', 'Pectoral mayor', 'thorax-anterior', 'abdominal', 'FMA45874', 'FMA45875', 'FJ1446'),
    ('pectoralisminor', 'Pectoral menor', 'thorax-anterior', None, 'FMA13375', 'FMA13376', 'FJ1456'),
    ('serratusanterior', 'Serrato anterior', 'thorax-anterior', None, 'FMA13398', 'FMA13399', 'FJ1459'),
    ('subclavius', 'Subclavio', 'thorax-anterior', None, 'FMA13412', 'FMA13411', 'FJ1460'),
    ('externaloblique', 'Oblicuo externo', 'abdomen', None, 'FMA13336', 'FMA13337', 'FJ1452'),
    ('trapezius', 'Trapecio', 'back', 'ascending', 'FMA33581', 'FMA33583', 'FJ1520'),
    ('trapezius', 'Trapecio', 'back', 'transverse', 'FMA33584', 'FMA33585', 'FJ1554'),
    ('trapezius', 'Trapecio', 'back', 'descending', 'FMA33586', 'FMA33587', 'FJ1521'),
    ('rhomboidmajor', 'Romboides mayor', 'back', None, 'FMA13381', 'FMA13382', 'FJ1536'),
    ('rhomboidminor', 'Romboides menor', 'back', None, 'FMA13383', 'FMA13384', 'FJ1537'),
    ('iliocostalislumborum', 'Iliocostal lumbar', 'back', None, 'FMA22740', 'FMA22741', 'FJ1527'),
    ('iliocostalisthoracis', 'Iliocostal torácico', 'back', None, 'FMA22742', 'FMA22743', 'FJ1528'),
    ('longissimusthoracis', 'Longísimo torácico', 'back', None, 'FMA22751', 'FMA22753', 'FJ1535'),
    ('spinalisthoracis', 'Espinoso torácico', 'back', None, 'FMA22779', 'FMA22780', 'FJ1544'),
    ('teresmajor', 'Redondo mayor', 'back', None, 'FMA32551', 'FMA32552', 'FJ1507'),
]
MODULE_FILES = {
    'thorax-anterior': 'muscular-torso-anterior.glb',
    'abdomen': 'muscular-abdomen.glb',
    'back': 'muscular-torso-posterior.glb',
}
REGION_LABELS = {'thorax-anterior': 'Tórax anterior', 'abdomen': 'Abdomen', 'back': 'Espalda'}
PART_LABELS = {'clavicular': 'porción clavicular', 'sternocostal': 'porción esternocostal',
               'abdominal': 'porción abdominal', 'ascending': 'porción ascendente',
               'transverse': 'porción transversa', 'descending': 'porción descendente'}


def sha(data):
    return hashlib.sha256(data).hexdigest()


def write_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8', newline='\n')


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--fetch', action='store_true')
args = parser.parse_args()
raw = {}
if args.fetch:
    CACHE.mkdir(parents=True, exist_ok=True)
    for name, expected in TABLES.items():
        with urllib.request.urlopen(BASE + name, timeout=60) as response:
            data = response.read()
        assert sha(data) == expected, 'Metadata changed: ' + name
        (CACHE / name).write_bytes(data)
    request = urllib.request.Request(ARCHIVE_URL, headers={
        'Range': f'bytes={CD_OFFSET}-{CD_OFFSET + CD_BYTES - 1}', 'Accept-Encoding': 'identity'})
    with urllib.request.urlopen(request, timeout=60) as response:
        assert response.status == 206
        assert response.headers.get('Content-Range') == f'bytes {CD_OFFSET}-{CD_OFFSET + CD_BYTES - 1}/{ARCHIVE_BYTES}'
        data = response.read(CD_BYTES + 1)
    assert len(data) == CD_BYTES and sha(data) == CD_SHA
    (CACHE / CD_NAME).write_bytes(data)
if SOURCE.exists() and not args.fetch:
    with zipfile.ZipFile(SOURCE) as archive:
        assert set(archive.namelist()) == set(TABLES) | {CD_NAME}
        raw = {name: archive.read(name) for name in archive.namelist()}
else:
    raw = {name: (CACHE / name).read_bytes() for name in [*TABLES, CD_NAME]}
for name, expected in {**TABLES, CD_NAME: CD_SHA}.items():
    assert sha(raw[name]) == expected, 'Pinned source mismatch: ' + name
prior_audit = json.loads((ROOT / 'docs/phase3/research/source-audit.json').read_text())
for record in prior_audit['metadata_audit']['metadata']:
    assert TABLES[record['filename']] == record['sha256']
    assert len(raw[record['filename']]) == record['bytes']
SOURCE.parent.mkdir(parents=True, exist_ok=True)
with zipfile.ZipFile(SOURCE, 'w', compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
    for name, data in sorted(raw.items()):
        info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
        info.compress_type = zipfile.ZIP_DEFLATED
        info.external_attr = 0o100644 << 16
        archive.writestr(info, data, compress_type=zipfile.ZIP_DEFLATED, compresslevel=9)

tables = {name: list(csv.DictReader(io.StringIO(raw[name].decode()), delimiter='\t')) for name in TABLES}
parts = {r['concept id']: r for r in tables['isa_parts_list_e.txt']}
edges = tables['isa_inclusion_relation_list.txt']
parents = {r['child id']: r for r in edges}
nonterminal = {r['parent id'] for r in edges}
bindings = collections.defaultdict(list)
for row in tables['isa_element_parts.txt']:
    bindings[row['concept id']].append(row['element file id'])
directory, offset = {}, 0
while offset < len(raw[CD_NAME]):
    header = struct.unpack_from('<4s6H3L5H2L', raw[CD_NAME], offset)
    assert header[0] == b'PK\x01\x02'
    path = raw[CD_NAME][offset + 46:offset + 46 + header[10]].decode()
    directory[Path(path).stem] = dict(path=path, bytes=header[9], compressedBytes=header[8],
        crc32=f'{header[7]:08x}', offset=header[16], method=header[4])
    offset += 46 + header[10] + header[11] + header[12]
assert len(directory) == 2234


def ancestry(cid):
    result = []
    while cid in parents:
        edge = parents[cid]
        result.append({'id': edge['parent id'], 'name': edge['parent name']})
        cid = edge['parent id']
    return result


def isa_type(cid):
    ids = {r['id'] for r in ancestry(cid)} | {cid}
    for key, value in [('FMA85453', 'head of muscle organ'), ('FMA10474', 'zone of muscle organ'),
                       ('FMA5022', 'muscle organ'), ('FMA55268', 'organ zone')]:
        if key in ids:
            return value
    return 'set/group or other anatomical entity'


def side_from_name(name):
    if 'right' in name:
        return 'right'
    if 'left' in name:
        return 'left'
    return 'unspecified'


approved = []
for family, label, region, component, right_id, left_id, fj in PAIRS:
    for side, cid, fid in [('right', right_id, fj), ('left', left_id, fj + 'M')]:
        row = parts[cid]
        assert bindings[cid] == [fid], (cid, bindings[cid])
        assert side_from_name(row['en']) == side
        assert fid in directory
        typ = isa_type(cid)
        parent = f'med3d:muscle:{family}:{side}' if component else f'muscular:region:{region}'
        if not component and family in {'iliocostalislumborum', 'iliocostalisthoracis', 'longissimusthoracis', 'spinalisthoracis'}:
            parent = 'muscular:group:back:erectors'
        elif not component and family in {'rhomboidmajor', 'rhomboidminor', 'teresmajor'}:
            parent = 'muscular:group:back:scapular'
        approved.append(dict(elementId=fid, sourceId=cid, representationId=row['representation id'],
            en=row['en'], name=label + (', ' + PART_LABELS[component] if component else ''),
            side=side, family=family, component=component,
            sourceType='muscle' if not component else ('head' if typ == 'head of muscle organ' else 'portion'),
            isaType=typ, isaAncestry=ancestry(cid), proposedParentId=parent,
            structureId=f'med3d:muscle:{family}:{side}' if component else 'bp3d:' + cid,
            regionId=f'muscular:region:{region}', moduleId='muscular:' + region,
            moduleFile=MODULE_FILES[region], archiveEntry=directory[fid],
            originalHeaderNotYetInspected=True))
assert len(approved) == 34 and len({r['structureId'] for r in approved}) == 26
assert len({r['elementId'] for r in approved}) == 34
approved_ids = {r['sourceId'] for r in approved}
approved_fj = {r['elementId'] for r in approved}
pilot = json.loads((ROOT / 'research/anatomy/muscular-pilot-source-lock.json').read_text())
assert not approved_fj.intersection(r['elementId'] for r in pilot['files'])

# A declared torso/scapular/deep-spinal search universe; not every body muscle.
candidate_pattern = re.compile(r'pectoralis|serratus|intercostal muscle|external oblique|trapezius|rhomboid|'
    r'iliocostalis|longissimus|spinalis|diaphragm|subclavius|teres major|rotator|intertransversar|'
    r'levatores costarum|levator scapulae|linea alba|transversus thoracis')
rejected = []
for cid, row in parts.items():
    if cid in approved_ids or cid in nonterminal or not candidate_pattern.search(row['en']):
        continue
    name = row['en']
    if 'intercostal muscle' in name:
        reason = 'Un FMA por clase y dos FJ; no identifica espacios costales ni lateralidad por concepto. No se presentará cada FJ como un músculo intercostal individual.'
    elif any(x in name for x in ['cervic', 'capitis']):
        reason = 'Cuello/cabeza fuera del alcance de Fase 3B; se conservan sólo las subdivisiones torácicas/lumbares aprobadas.'
    elif 'diaphragm' in name:
        reason = 'Presente e identificable; aplazado por alcance: esta entrega se limita a paredes del torso y transición escapular.'
    elif 'linea alba' in name:
        reason = 'Estructura aponeurótica clasificada como unión anatómica, no un músculo; no se añade como unidad muscular.'
    elif 'levator scapulae' in name:
        reason = 'Identificable, aplazado para contener la extensión cervical; la transición escapular usa romboides y redondo mayor.'
    elif any(x in name for x in ['rotator', 'interspinalis', 'intertransversar', 'levatores costarum']):
        reason = 'Conjunto/representación segmentaria sin desglose vertebral o costal completo verificable; requiere una curación específica posterior.'
    else:
        reason = 'Identificable, aplazado para mantener un conjunto acotado; la espalda profunda ya incluye cuatro subdivisiones verificadas de erectores.'
    fids = bindings[cid]
    rejected.append(dict(sourceId=cid, representationId=row['representation id'], en=name,
        side=side_from_name(name), sourceType=isa_type(cid), elementIds=fids,
        reason=reason, archiveEntries={fid: directory[fid] for fid in fids}))
# The generic spinalis class has two files with no narrower represented concept.
unresolved_spinalis = sorted(set(bindings['FMA77179']) - set(bindings['FMA22765']))
if unresolved_spinalis:
    rejected.append(dict(sourceId='FMA77179', representationId=parts['FMA77179']['representation id'],
        en='spinalis — elements without narrower represented concept', side='unspecified',
        sourceType='group/unresolved subdivision', elementIds=unresolved_spinalis,
        reason='FJ1543/FJ1543M no tienen una subdivisión nominal más específica representada; no se adivina región, lateralidad o identidad por el número de archivo.',
        archiveEntries={fid: directory[fid] for fid in unresolved_spinalis}))
rejected.sort(key=lambda r: (r['en'], r['sourceId']))
rejected_fj = {fid for r in rejected for fid in r['elementIds']}
assert not approved_fj & rejected_fj

search_terms = ['abdom', 'obliq', 'transvers', 'latiss', 'rectus', 'quadratus', 'pyramid', 'multif']
search_results = {term: {name: [{'sourceId': r['concept id'], 'en': r['en']}
    for r in tables[name] if term in r['en'].lower()]
    for name in ['isa_parts_list_e.txt', 'partof_parts_list_e.txt']} for term in search_terms}
missing = [
    ('rectus abdominis', r'rectus.*abdom|abdom.*rectus'),
    ('internal oblique', r'internal.*obliq|obliq.*intern'),
    ('transversus abdominis', r'transvers.*abdom|abdom.*transvers'),
    ('latissimus dorsi', r'latiss'),
    ('quadratus lumborum', r'quadratus.*lumb|lumb.*quadratus'),
    ('pyramidalis', r'pyramid'), ('multifidus', r'multif'),
]
absences = []
for name, pattern in missing:
    matches = [r for table in ['isa_parts_list_e.txt', 'partof_parts_list_e.txt']
               for r in tables[table] if re.search(pattern, r['en'], re.I)]
    assert not matches, (name, matches)
    absences.append(dict(name=name, query=pattern,
        status='No identified concept/binding in the two inspected English 4.0 export tables; not a claim about all BP3D versions or the living body.'))
families = sorted({r['family'] for r in approved})
modules = []
for region, filename in MODULE_FILES.items():
    members = [r for r in approved if r['moduleId'] == 'muscular:' + region]
    modules.append(dict(id='muscular:' + region, filename=filename,
        regionId='muscular:region:' + region, meshes=len(members),
        structures=len({r['structureId'] for r in members}),
        upstreamObjBytes=sum(r['archiveEntry']['bytes'] for r in members),
        upstreamCompressedBytes=sum(r['archiveEntry']['compressedBytes'] for r in members)))
audit = dict(phase='3B', decision='approved-local-pre-extraction', checkedDate='2026-09-21',
    baselineCommit='84b4c9ababb9b1360a09ec03c77c96d0b7c748e6',
    source=dict(name='BodyParts3D 4.0 OBJ99 / DBCLS', url=ARCHIVE_URL, archiveBytes=ARCHIVE_BYTES,
        centralDirectoryOffset=CD_OFFSET, centralDirectoryBytes=CD_BYTES, centralDirectorySha256=CD_SHA,
        archiveEntries=2234, fullArchiveDownloaded=False, geometryExtractedDuringAudit=False,
        metadataArchive='research/anatomy/torso-metadata.zip', metadataArchiveSha256=sha(SOURCE.read_bytes())),
    metadataChecks=[dict(filename=name, url=BASE + name, bytes=len(raw[name]), sha256=sha(raw[name]),
        matchesPhase3AAudit=name != 'partof_inclusion_relation_list.txt') for name in TABLES],
    counts=dict(families=len(families), structures=26, meshes=34, rejectedConceptRows=len(rejected),
        rejectedUniqueElements=len(rejected_fj), reviewedUniqueElements=len(approved_fj | rejected_fj),
        absentRequestedFamilies=len(absences),
        definition='34 selected FJ elements form 26 side-specific muscles in 13 families. Candidate totals cover the declared torso/scapular/deep-spinal term search, not the whole body. Aggregate ancestors are not counted again.'),
    modules=modules, approved=approved, rejected=rejected, absent=absences,
    discovery=dict(candidatePattern=candidate_pattern.pattern, broadNameQueries=search_results),
    groupingNotes=[
        'Editorial muscle parents aggregate the three named pectoralis major/trapezius portions; no IS-A edge is promoted to PART-OF.',
        'PART-OF names pectoralis major FMA13373/FMA13374 but includes only sternocostal and abdominal portions. Its omission of the clavicular portion is preserved as export incompleteness.',
        'Clavicular pectoralis is labelled part but classified under head of muscle organ. Both classifications are preserved.',
        'Ascending and descending trapezius are under organ zone FMA55268, outside the previous 403-element union. The transverse portion is under zone of muscle organ.',
        'The four selected erector subdivisions do not represent the complete erector spinae group. No synthetic complete-group geometry is created.',
        'Back is an editorial study region. Teres major belongs to the scapulohumeral transition, not to intrinsic spinal musculature.',
        'No source OBJ header, geometry, vertex count, triangle count or anatomical fit is claimed validated by this metadata audit.',
    ],
    groupingSources=[
        'https://openstax.org/books/anatomy-and-physiology-2e/pages/11-4-axial-muscles-of-the-abdominal-wall-and-thorax',
        'https://openstax.org/books/anatomy-and-physiology-2e/pages/11-5-muscles-of-the-pectoral-girdle-and-upper-limbs',
        BASE + 'partof_inclusion_relation_list.txt',
    ])
write_json(OUTPUT, audit)

lines = ['# Fase 3B — auditoría previa y decisión de inventario', '',
    'Base: `84b4c9ababb9b1360a09ec03c77c96d0b7c748e6`. Revisión de metadatos: 21 de septiembre de 2026.', '',
    '**Decisión: 13 familias bilaterales, 26 músculos y 34 elementos originales.** Esta selección se fija antes de extraer o convertir OBJ. Se amplía el torso anterior, el oblicuo externo y la espalda con transición escapular; no se afirma cobertura completa del torso.', '',
    'Se volvieron a leer las seis tablas oficiales de BP3D 4.0. Las cinco ya auditadas en Fase 3A conservan sus SHA-256; se añade la tabla real PART-OF de relaciones. El directorio ZIP de 170.025 bytes coincide con el hash fijado y contiene los 34 seleccionados. Esta auditoría no extrae geometría ni procesa descartados.', '',
    'La [selección estructurada](../research/anatomy/torso-selection.json) conserva cada FMA/FJ, representación BP, clasificación IS-A, ascendencia, lateralidad explícita, padre editorial, módulo, tamaños y CRC declarados. Los [metadatos originales](../research/anatomy/torso-metadata.zip) permiten reproducir la decisión sin red:', '',
    '```sh', 'python scripts/anatomy/audit-torso-inventory.py', '```', '',
    '`--fetch` verifica y vuelve a obtener sólo las seis tablas y el directorio mediante Range exacto; nunca descarga OBJ ni el ZIP completo.', '',
    '## Conjunto aprobado', '',
    '| Nombre | FMA | FJ | Lado | Tipo fuente | Padre propuesto | Región | Módulo |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |']
for row in approved:
    region = row['regionId'].split(':')[-1]
    lines.append(f"| {row['name']} | {row['sourceId']} | {row['elementId']} | {row['side']} | {row['isaType']} | `{row['proposedParentId']}` | {REGION_LABELS[region]} | `{row['moduleId']}` |")
lines += ['', '## Tamaños declarados y módulos previstos', '',
    '| Módulo | Músculos | Mallas | Bytes OBJ declarados | Bytes comprimidos upstream |',
    '| --- | ---: | ---: | ---: | ---: |']
for module in modules:
    lines.append(f"| `{module['filename']}` | {module['structures']} | {module['meshes']} | {module['upstreamObjBytes']} | {module['upstreamCompressedBytes']} |")
lines += ['', 'Estos tamaños proceden del directorio, no son métricas de GLB ni memoria GPU. El oblicuo externo es la pareja más pesada y justifica un módulo abdominal liberable independiente; se conservará la geometría y se medirá el resultado.', '',
    '## Identidad, agrupación y límites', '',
    'Los padres editoriales de pectoral mayor y trapecio reúnen sus porciones publicadas, sin contar cada porción como un músculo. El pectoral clavicular está clasificado como `head of muscle organ`, aunque su nombre fuente dice `part`; se conservan ambos datos. PART-OF reconoce pectoral mayor derecho/izquierdo (FMA13373/FMA13374), pero omite la porción clavicular. No se presenta ese export incompleto como prueba de ausencia de la porción.', '',
    'Las porciones ascendente y descendente del trapecio pertenecen directamente a `organ zone`, fuera de las tres ramas que produjeron los 403 candidatos de Fase 3A. Por eso esta auditoría recorre el inventario nominal completo. No se cambia la documentación histórica de aquella consulta ni se toma su unión como inventario muscular exhaustivo.', '',
    'Las subdivisiones iliocostal lumbar/torácica, longísimo torácico y espinoso torácico sustentan un grupo editorial parcial de erectores espinales. Los romboides y el redondo mayor permiten estudiar la transición escapular sin duplicar el manguito rotador de Fase 3A. «Espalda» es una región de navegación; el redondo mayor no se clasifica como músculo intrínseco espinal. Estas agrupaciones se apoyan en [OpenStax sobre pared abdominal/tórax](https://openstax.org/books/anatomy-and-physiology-2e/pages/11-4-axial-muscles-of-the-abdominal-wall-and-thorax) y [cintura escapular/miembro superior](https://openstax.org/books/anatomy-and-physiology-2e/pages/11-5-muscles-of-the-pectoral-girdle-and-upper-limbs), además de la identidad explícita de las porciones.', '',
    '## Candidatos encontrados y descartados', '',
    f"Se revisaron {len(approved_fj | rejected_fj)} FJ únicos dentro de la búsqueda declarada: 34 aprobados y {len(rejected_fj)} descartados en {len(rejected)} filas conceptuales. Los conceptos antecesores agregados no se vuelven a contar. No es un censo de toda la musculatura humana.", '',
    '| Concepto fuente | FMA | FJ | Motivo de descarte |', '| --- | --- | --- | --- |']
for row in rejected:
    lines.append(f"| {row['en']} | {row['sourceId']} | {', '.join(row['elementIds'])} | {row['reason']} |")
lines += ['', '## Ausencias comprobadas en este export', '',
    'No se identificaron conceptos/bindings de recto abdominal, oblicuo interno, transverso abdominal, dorsal ancho, cuadrado lumbar, piramidal o multífido en las tablas inglesas IS-A/PART-OF inspeccionadas. Se buscaron también los fragmentos `abdom`, `obliq`, `transvers`, `latiss`, `rectus`, `quadratus`, `pyramid` y `multif`, conservando los resultados en JSON. Esto limita la cobertura de abdomen a oblicuo externo; no se completan los huecos con otra fuente ni con geometría fabricada.', '',
    'La ausencia se refiere a este export 4.0 y sus tablas, no a toda versión de BP3D. Los FJ vecinos 1453M/1457M/1458M corresponden al elevador del ano; no son músculos abdominales mal nombrados. No se importan por proximidad numérica de sus archivos.', '',
    'La siguiente etapa comprobará las cabeceras originales y hashes, vértices/caras/triángulos, bounds, transformación compartida y GLB decodificado. Esta decisión por metadatos no valida registro anatómico, contacto con huesos ni precisión clínica.', '']
DOC.write_text('\n'.join(lines), encoding='utf-8', newline='\n')
print(json.dumps({'selection': str(OUTPUT), 'counts': audit['counts'], 'modules': modules,
                  'metadataZipBytes': SOURCE.stat().st_size}, ensure_ascii=False))
