#!/usr/bin/env python3
"""Reproduce Phase 3DE metadata-only decisions before any OBJ extraction.

Reads the preserved six BP3D metadata tables and pinned ZIP central directory.
Reuses the unchanged pinned Phase 3B metadata archive; no network requests.
No OBJ is extracted, parsed, converted, or generated by this script.
"""
from __future__ import annotations
import argparse
import collections
import csv
import hashlib
import io
import json
import re
import struct
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASE = 'https://dbarchive.biosciencedbc.jp/data/bodyparts3d/20130619/'
CACHE = ROOT / '.cache/bodyparts3d-4.0/metadata'
SOURCE = ROOT / 'research/anatomy/torso-metadata.zip'
OUTPUT = ROOT / 'research/anatomy/head-neck-selection.json'
DOC = ROOT / 'docs/phase3de-audit.md'
TABLES = {
    'isa_parts_list_e.txt': 'ab7796deedd49205e77f3609a1cb8c53e2bbee14ecb5c9a6ca05227469780513',
    'isa_element_parts.txt': 'a3de74423f943b0d724ae8f59b3a817f87c423a544f8db98113b1980817cbeaf',
    'isa_inclusion_relation_list.txt': '26e7d818e03a8c909fe09c561f38d0d513423c87681f9450a803bc38f5b07564',
    'partof_parts_list_e.txt': '9224080557053e6f1322f1e13ab27f0ecde0db19bb3b505f0631afad230eeebd',
    'partof_element_parts.txt': '3f5f6df1028eb122b30de77c711597b6bb8e5541658e5985859fd228adbf88ea',
    'partof_inclusion_relation_list.txt': '1b40738270931e3c1d955ce34e0fce0d8d10d8c5ad543463e40b4b4c0243007c',
}
CD_NAME = 'isa_BP3D_4.0_obj_99.central-directory.bin'
CD_OFFSET, CD_BYTES, ARCHIVE_BYTES = 142733851, 170025, 142903898
CD_SHA = 'edde15c7c5f34b2b9743935fb3c1873cce3a9789164427ddf8343c879bcde96b'
ARCHIVE_URL = BASE + 'isa_BP3D_4.0_obj_99.zip'


def sha(data):
    return hashlib.sha256(data).hexdigest()


def write_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8', newline='\n')


with zipfile.ZipFile(SOURCE) as archive:
    assert set(archive.namelist()) == set(TABLES) | {CD_NAME}
    raw = {name: archive.read(name) for name in archive.namelist()}
for name, expected in {**TABLES, CD_NAME: CD_SHA}.items():
    assert sha(raw[name]) == expected, 'Pinned source mismatch: ' + name

tables = {name: list(csv.DictReader(io.StringIO(raw[name].decode()), delimiter='\t')) for name in TABLES}
parts = {r['concept id']: r for r in tables['isa_parts_list_e.txt']}
edges = tables['isa_inclusion_relation_list.txt']
parents = {r['child id']: r for r in edges}
nonterminal = {r['parent id'] for r in edges}
bindings = collections.defaultdict(list)
for row in tables['isa_element_parts.txt']:
    bindings[row['concept id']].append(row['element file id'])
directory, offset = {}, 0
while offset < len(raw[CD_NAME]):
    header = struct.unpack_from('<4s6H3L5H2L', raw[CD_NAME], offset)
    assert header[0] == b'PK\x01\x02'
    path = raw[CD_NAME][offset + 46:offset + 46 + header[10]].decode()
    directory[Path(path).stem] = dict(path=path, bytes=header[9], compressedBytes=header[8],
        crc32=f'{header[7]:08x}', offset=header[16], method=header[4])
    offset += 46 + header[10] + header[11] + header[12]
assert len(directory) == 2234


def ancestry(cid):
    result = []
    while cid in parents:
        edge = parents[cid]
        result.append({'id': edge['parent id'], 'name': edge['parent name']})
        cid = edge['parent id']
    return result


def isa_type(cid):
    ids = {r['id'] for r in ancestry(cid)} | {cid}
    for key, value in [('FMA85453', 'head of muscle organ'), ('FMA10474', 'zone of muscle organ'),
                       ('FMA5022', 'muscle organ'), ('FMA55268', 'organ zone')]:
        if key in ids:
            return value
    return 'set/group or other anatomical entity'


def side_from_name(name):
    if 'right' in name:
        return 'right'
    if 'left' in name:
        return 'left'
    return 'unspecified'



# Names, FMA and FJ are explicit pairs from the regional metadata inspection.
PAIRS = [
 ('sternocleidomastoid','Esternocleidomastoideo','sternocleidomastoideus','superficial','FMA13408','FMA13409','FJ1595','FJ1573'),
 ('platysma','Platisma','platysma','superficial','FMA45739','FMA45740','FJ1587','FJ1558'),
 ('scalenusanterior','Escaleno anterior','scalenus anterior','lateral','FMA13392','FMA13393','FJ1592','FJ1570'),
 ('scalenusmedius','Escaleno medio','scalenus medius','lateral','FMA13390','FMA13391','FJ1593','FJ1571'),
 ('scalenusposterior','Escaleno posterior','scalenus posterior','lateral','FMA13388','FMA13389','FJ1594','FJ1572'),
 ('longuscapitis','Largo de la cabeza','longus capitis','prevertebral','FMA46309','FMA46310','FJ1582','FJ1561'),
 ('spleniuscapitis','Esplenio de la cabeza','splenius capitis','posterior','FMA22728','FMA22729','FJ1545','FJ1545M'),
 ('sternohyoid','Esternohioideo','sternohyoideus','infrahyoid','FMA13346','FMA13347','FJ1596','FJ1574'),
 ('mylohyoid','Milohioideo','mylohyoideus','suprahyoid','FMA46321','FMA46322','FJ1583','FJ1562'),
 ('geniohyoid','Genihioideo','geniohyoideus','suprahyoid','FMA46326','FMA46327','FJ1580','FJ1559'),
]
pattern = re.compile(r'masseter|temporalis|pterygoid|orbicularis|buccinator|zygomaticus|frontalis|occipitalis|occipitofrontal|sternocleidomastoid|platysma|scalen|levator scapula|longus colli|longus capitis|digastric|mylohyoid|geniohyoid|stylohyoid|sternohyoid|sternothyroid|thyrohyoid|omohyoid|splenius|semispinalis capitis|semispinalis cervicis|rectus capitis|obliquus capitis|risorius|nasalis|procerus|corrugator|depressor (anguli|labii|septi)|levator (labii|anguli)',re.I)
existing=json.loads((ROOT/'public/models/anatomy/muscular/catalog.json').read_text(encoding='utf-8'))
# Rerunning this bounded audit must ignore its own already integrated cohort.
historical_nodes=[n for n in existing['nodes'] if 'muscular:neck' not in n.get('assetIds',[])]
old_ids={n['sourceId'] for n in historical_nodes if n.get('sourceId')}
old_fj={alias for n in historical_nodes for alias in n['aliases'] if re.fullmatch(r'FJ[0-9]+M?',alias)}
approved=[]
for family,label,latin,division,right,left,rf,lf in PAIRS:
 for side,cid,fid in [('right',right,rf),('left',left,lf)]:
  r=parts[cid]
  assert bindings[cid]==[fid] and side_from_name(r['en'])==side and isa_type(cid)=='muscle organ'
  assert cid not in old_ids and fid not in old_fj
  assert fid in directory
  approved.append(dict(elementId=fid,sourceId=cid,representationId=r['representation id'],en=r['en'],name=label,
   latin='Musculus '+latin,side=side,family=family,component=None,region='neck',compartment=division,
   sourceType='muscle',isaType='muscle organ',isaAncestry=ancestry(cid),structureId='bp3d:'+cid,
   muscleParent='No aplica: músculo',proposedParentId='muscular:region:neck:'+division,regionId='muscular:region:neck',
   moduleId='muscular:neck',moduleFile='muscular-neck.glb',archiveEntry=directory[fid],
   decision='APROBADO',reason='Músculo con identidad y lateralidad explícitas, un FJ propio por lado y sin duplicación histórica.',
   originalHeaderNotYetInspected=True))
approved_ids={r['sourceId'] for r in approved}
other=[]
for cid,r in parts.items():
 if cid in approved_ids or cid in nonterminal or not bindings[cid] or not pattern.search(r['en']):continue
 typ=isa_type(cid);fids=bindings[cid];decision='APLAZADO'
 reason='Identificable, aplazado para limitar esta cohorte a diez familias cervicales; no se afirma ausencia ni ambigüedad.'
 if typ not in ['muscle organ','head of muscle organ','zone of muscle organ']:
  decision='DESCARTADO';reason='Membrana o ligamento: no es una unidad muscular y no se integra.'
 elif len(fids)!=1:reason='Varios FJ por músculo; desglose de vientres/componentes pendiente. No se transforma cada FJ en un músculo.'
 elif 'longus colli' in r['en']:reason='Zonas de un músculo, con desglose terminal lateral asimétrico en esta tabla; requiere curación adicional, sin reflejar ni inventar el lado faltante.'
 if cid in old_ids or set(fids)&old_fj:
  decision='DESCARTADO';reason='Ya integrado: se conserva la identidad previa sin duplicación.'
 other.append(dict(sourceId=cid,representationId=r['representation id'],en=r['en'],name=r['en'],elementIds=fids,
  side=side_from_name(r['en']),isaType=typ,isaAncestry=ancestry(cid),
  muscleParent='No aplica: músculo' if typ=='muscle organ' else 'Por curar' if 'muscle' in typ else 'No aplica',
  region='neck',compartment='No asignado',moduleId='No asignado',decision=decision,reason=reason,
  archiveEntries={fid:directory[fid] for fid in fids}))
other.sort(key=lambda r:(r['en'],r['sourceId']))
missing=[]
for label,term in [('Masetero','masseter'),('Temporal','temporalis'),('Pterigoideo medial','medial pterygoid'),
 ('Pterigoideo lateral','lateral pterygoid'),('Orbicular de los ojos','orbicularis oculi'),('Orbicular de la boca','orbicularis oris'),
 ('Buccinador','buccinator'),('Cigomático mayor','zygomaticus major'),('Cigomático menor','zygomaticus minor'),
 ('Occipitofrontal','occipitofrontal|frontalis|occipitalis'),('Risorio','risorius'),('Nasal','nasalis'),('Prócer','procerus'),('Corrugador superciliar','corrugator')]:
 matches=[r for t in ['isa_parts_list_e.txt','partof_parts_list_e.txt'] for r in tables[t] if re.search(term,r['en'],re.I)]
 assert not matches,(label,matches)
 missing.append(dict(name=label,query=term,sourceId=None,elementId=None,decision='APLAZADO',reason='Sin identificación nominal en las dos tablas BP3D 4.0 consultadas; no se asignan FMA/FJ ni geometría supuesta.'))
counts=dict(families=10,structures=20,meshes=20,modules=1,candidates=len(approved)+len(other),approvedConceptRows=20,
 discardedConceptRows=sum(r['decision']=='DESCARTADO' for r in other),deferredConceptRows=sum(r['decision']=='APLAZADO' for r in other),
 requestedFamiliesWithoutIdentification=len(missing))
modules=[dict(id='muscular:neck',filename='muscular-neck.glb',regionId='muscular:region:neck',meshes=20,structures=20,
 upstreamObjBytes=sum(r['archiveEntry']['bytes'] for r in approved),upstreamCompressedBytes=sum(r['archiveEntry']['compressedBytes'] for r in approved))]
audit=dict(phase='3DE',decision='approved-local-pre-extraction',checkedDate='2026-09-23',baselineCommit='5ba794438287a16b6482c6a63d3d2b6ca8ee6542',
 source=dict(name='BodyParts3D 4.0 OBJ99 / DBCLS',url=ARCHIVE_URL,archiveBytes=ARCHIVE_BYTES,centralDirectorySha256=CD_SHA,
 metadataArchive='research/anatomy/torso-metadata.zip',fullArchiveDownloaded=False,geometryExtractedDuringAudit=False),
 counts=counts,modules=modules,approved=approved,other=other,missingRequestedFamilies=missing,
 discovery=dict(candidatePattern=pattern.pattern,scope='Only matching terminal concepts with FJ; separate absence queries in both name tables.',
 isaNameRows=len(tables['isa_parts_list_e.txt']),partofNameRows=len(tables['partof_parts_list_e.txt'])),
 notes=['No nueva región muscular Cabeza sin cobertura: músculos faciales/masticatorios no identificados en estas tablas.',
 'Un solo módulo cervical bilateral: 20 mallas, seis divisiones con cobertura; no un GLB por músculo.',
 'IS-A sólo se conserva como clasificación. Padres regionales editoriales, sin afirmar aristas PART-OF.',
 'Las ausencias nominales no prueban ausencia en todas las versiones de BP3D. No se cambia de versión/fuente.',
 'Esta auditoría no reabre las auditorías de 3A/3B/3C; sólo lee sus IDs para evitar duplicados.'])
write_json(OUTPUT,audit)
lines=['# Fase 3DE — auditoría regional previa','',
 'Base: `5ba794438287a16b6482c6a63d3d2b6ca8ee6542`. Fuente: BP3D 4.0 OBJ99 / DBCLS. Metadatos preservados de 3B, sin extraer OBJ durante esta decisión.','',
 'Selección: **10 familias bilaterales, 20 músculos y 20 mallas en un módulo cervical**. Se conserva el cuello superficial, lateral, prevertebral, posterior y los grupos supra/infrahioideos con cobertura verificada.','',
 f"Conceptos candidatos: {counts['candidates']}; aprobados 20; descartados {counts['discardedConceptRows']}; aplazados {counts['deferredConceptRows']}. Además, {len(missing)} familias solicitadas sin identificación nominal se registran aparte, sin inventar FMA/FJ.",'',
 'Las tablas de esta versión no identifican masetero, temporal, pterigoideos ni los músculos faciales consultados. No se crea una región Cabeza vacía ni se usa otra fuente para rellenarla. La expresión facial del platisma se estudia desde su región cervical.','',
 '[Selección y criterios reproducibles](../research/anatomy/head-neck-selection.json). `python scripts/anatomy/audit-head-neck-inventory.py` reproduce esta decisión sin red ni OBJ. [Antecedentes 3C](phase3c-delivery.md).','',
 '| Nombre | FMA | FJ | Lado | Tipo | Músculo padre | Región | Módulo | Decisión | Motivo |','|---|---|---|---|---|---|---|---|---|---|']
for r in approved+other:
 lines.append('| '+' | '.join(str(v).replace('|','/') for v in [r['name'],r['sourceId'],', '.join(r.get('elementIds',[r.get('elementId')])),r['side'],r['isaType'],r['muscleParent'],r['region'],r['moduleId'],r['decision'],r['reason']])+' |')
lines+=['','## Consultas sin identificación nominal','', '| Familia | Decisión | Motivo |','|---|---|---|']
for r in missing:lines.append(f"| {r['name']} | {r['decision']} | {r['reason']} |")
lines+=['','La integración exige aún comprobar cabeceras originales, conservación geométrica y coincidencia espacial. Ninguna aprobación nominal equivale a certificación clínica.','']
DOC.write_text('\n'.join(lines),encoding='utf-8',newline='\n')
print(json.dumps(dict(**counts,selectionSha256=sha(OUTPUT.read_bytes())),indent=2))
