// Fase 3C evidence from the production build and actual WebGL objects.
// Geometry, visibility and opacity are inspected through the read-only ?qa=1 bridge.
import assert from 'node:assert/strict';
import {readFile, writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createHarness, project, setSlider, withinQaDeadline} from './browser-qa.mjs';
import {limbsCatalog,PHASE3C_ASSET_IDS,PHASE3C_MODULE_QUERY} from './limbs-catalog.mjs';
import {PILOT_ASSET_IDS} from './pilot-catalog.mjs';
import {PHASE3B_ASSET_IDS} from './torso-catalog.mjs';

const mode=process.argv.find(arg=>['--functional','--captures','--performance'].includes(arg))?.slice(2)||'functional';
const h=await createHarness({output:process.env.QA_OUTPUT_DIR||path.join(project,'.qa-anatomy','limbs',mode),viewport:{width:1440,height:900},reducedMotion:mode==='captures'?'reduce':'no-preference'});
const {page,output}=h;
const rawGoto=page.goto.bind(page);
page.goto=(url,options)=>{const target=new URL(url);if(target.pathname.endsWith('/anatomia/')&&!target.searchParams.has('modules'))target.searchParams.set('modules',PHASE3C_ASSET_IDS.join(','));return rawGoto(target.href,options);};

const muscular=limbsCatalog(JSON.parse(await readFile(path.join(project,process.env.QA_SERVE_DIR||'dist','models/anatomy/muscular/catalog.json'),'utf8')));
const nodes=[...h.catalog.nodes,...muscular.nodes],assets=[...h.catalog.assets,...muscular.assets],byId=new Map(nodes.map(node=>[node.id,node]));
const limbsAssets=muscular.assets.filter(asset=>asset.provenanceId==='bodyparts3d-4.0-muscular-limbs');
const limbsAssetIds=new Set(limbsAssets.map(asset=>asset.id));
const limbsNodes=muscular.nodes.filter(node=>node.assetIds.some(id=>limbsAssetIds.has(id)));
const wholeLimbs=limbsNodes.filter(node=>node.kind==='structure');
const boneMeshes=h.expectedMeshes,muscleMeshes=muscular.coverage.meshes,totalMeshes=boneMeshes+muscleMeshes;
const sum=(list,key)=>list.reduce((total,item)=>total+item[key],0);
const report={date:new Date().toISOString(),mode,source:'Local production build over unthrottled loopback HTTP; no-store responses',environment:{browser:'Headless Chromium',renderer:'ANGLE SwiftShader software WebGL',deviceScaleFactor:1,physicalGpuTested:false},checks:[],captures:[],measurements:{},errors:h.errors,badRequests:h.badRequests};
const check=(name,value={})=>{report.checks.push({name,...value});console.log('PASS',name,JSON.stringify(value));};
const wait=ms=>page.waitForTimeout(ms);
const snapshot=()=>page.evaluate(()=>window.__med3dAtlasScene());
const parts=async()=>[...(await snapshot()).parts].sort((a,b)=>a.id.localeCompare(b.id));
const positions=list=>list.map(part=>({id:part.id,position:part.position,restPosition:part.restPosition}));
const selectedName=()=>page.locator('.atlas-detail-content h2').textContent();
const systemInput=id=>page.locator(`[data-system-id="${id}"] .atlas-layer-toggle input`);
const assetInput=asset=>page.locator(`[data-system-id="${asset.systemId}"] [data-asset-id="${asset.id}"]`).getByRole('checkbox');
function muscle(family,side='right') {const matches=wholeLimbs.filter(node=>node.family===family&&node.side===side);assert.equal(matches.length,1,`One approved ${family} ${side}`);return matches[0];}
function descendants(id) {const ids=new Set([id]);for(const child of byId.get(id)?.children||[])for(const value of descendants(child))ids.add(value);return ids;}
const ownedParts=node=>muscular.nodes.filter(candidate=>descendants(node.id).has(candidate.id)&&candidate.meshNames.length);
async function structures(){if(!await page.getByRole('textbox',{name:'Buscar estructura anatómica'}).isVisible())await page.getByRole('button',{name:'Estructuras',exact:true}).click();}
async function clearSearch(){await structures();await page.getByRole('textbox',{name:'Buscar estructura anatómica'}).fill('');}
async function layers(){await clearSearch();await page.getByRole('button',{name:'Capas',exact:true}).click();}
async function choose(node){assert.ok(node,'Catalog target exists');await structures();await page.getByRole('textbox',{name:'Buscar estructura anatómica'}).fill(node.name);await page.locator(`.atlas-search-result[data-node-id="${node.id}"]`).click();await page.waitForFunction(name=>document.querySelector('.atlas-detail-content h2')?.textContent===name,node.name);await wait(850);}
async function closePanels(){for(const name of ['Cerrar estructuras','Cerrar inspección']){const button=page.getByRole('button',{name,exact:true});if(await button.isVisible())await button.click();}}
async function action(name,settle=400){const button=page.locator('.atlas-selection-actions').getByRole('button',{name,exact:true});if(!await button.isVisible())await page.getByRole('button',{name:'Inspección',exact:true}).click();await button.click();if(settle)await wait(settle);}
async function goto(systems='skeletal,muscular',moduleIds){const expected=assets.filter(asset=>systems.split(',').includes(asset.systemId)&&(asset.systemId!=='muscular'||!moduleIds||moduleIds.includes(asset.id)));await page.goto(h.origin+'/med3d/anatomia/?qa=1&systems='+systems+(moduleIds?'&modules='+moduleIds.join(','):''),{waitUntil:'domcontentloaded'});await h.waitMeshes(sum(expected,'meshCount'));await wait(700);return expected;}
async function reset(){await page.getByRole('button',{name:'Restablecer atlas'}).click();await h.waitMeshes(totalMeshes);await wait(1100);}
async function opacity(value){await layers();await setSlider(page.locator('[data-system-id="muscular"] .atlas-layer-opacity input'),value);await page.waitForFunction(value=>{const muscles=window.__med3dAtlasScene().parts.filter(part=>part.systemId==='muscular');return muscles.length>0&&muscles.every(part=>Math.abs(part.opacity-value/100)<1e-8&&part.transparent===(value<100)&&part.depthWrite===(value===100));},value);await wait(350);}
async function explode(level,value){await page.getByRole('combobox',{name:'Nivel de despiece'}).selectOption(level);await setSlider(page.getByRole('slider',{name:'Separación de piezas'}),value);await page.waitForFunction(value=>{const parts=window.__med3dAtlasScene().parts;return parts.length&&parts.every(part=>part.position.every((position,i)=>position===part.targetPosition[i]))&&(value===0?parts.every(part=>part.position.every((position,i)=>position===part.restPosition[i])):parts.some(part=>part.position.some((position,i)=>position!==part.restPosition[i])));},value,{timeout:120000});}
async function atRest(){const values=await parts();for(const part of values)assert.deepEqual(part.position,part.restPosition,'Exact rest position '+part.id);return positions(values);}
async function shot(name,note=''){await page.mouse.move(10,10);await wait(200);await page.screenshot({path:path.join(output,name+'.png'),fullPage:false});report.captures.push({file:name+'.png',viewport:page.viewportSize(),selection:await selectedName(),note,metrics:await h.metrics(),scene:await snapshot()});console.log('CAPTURE',name);}
async function context(node){await choose(node);await page.getByRole('button',{name:'Mostrar contexto',exact:true}).click();await wait(700);const visible=(await parts()).filter(part=>part.visible),own=descendants(node.id);assert.ok(visible.some(part=>part.systemId==='skeletal'));assert.ok(visible.some(part=>part.systemId==='muscular'));assert.ok(visible.filter(part=>part.systemId==='muscular').every(part=>own.has(part.id)));assert.ok(visible.length<totalMeshes);return visible.map(part=>part.id);}

async function functional(){
  await goto();const initial=await h.metrics();
  assert.deepEqual(new Set(limbsAssets.map(asset=>asset.id)),new Set(['gluteal','thigh','leg','forearm'].flatMap(region=>['right','left'].map(side=>'muscular:'+region+'-'+side))));
  assert.equal(wholeLimbs.length,48);assert.equal(sum(limbsAssets,'meshCount'),54);assert.equal(muscleMeshes,114);assert.equal(totalMeshes,319);assert.equal(initial.loadedAssets,20);assert.equal(initial.triangleCount,sum(assets,'triangles'));
  check('Full registered body loads original pilot plus 48 limb muscles / 54 new meshes',initial);
  for(const asset of limbsAssets){await goto('muscular',[asset.id]);const state=await h.metrics();assert.equal(state.triangleCount,asset.triangles);assert.equal(state.loadedAssets,1);assert.ok((await parts()).every(part=>part.assetId===asset.id));await layers();await assetInput(asset).uncheck();await h.waitMeshes(0);assert.equal((await h.metrics()).geometryBytes,0);await assetInput(asset).check();await h.waitMeshes(asset.meshCount);assert.equal((await h.metrics()).geometryBytes,state.geometryBytes);check('Independent limbs module load, full release and reload '+asset.id,{meshes:asset.meshCount,geometryBytes:state.geometryBytes});}
  await goto();
  const rectus=muscle('rectusfemoris'),sartorius=muscle('sartorius'),posterior=muscle('bicepsfemoris'),deep=muscle('tibialisposterior');
  for(const node of wholeLimbs){await choose(node);const education=page.getByRole('region',{name:'Información muscular de '+node.name,exact:true});for(const heading of ['Origen','Inserción','Inervación'])assert.ok(await education.getByRole('heading',{name:heading,exact:true}).count());assert.ok(await education.locator('a[href^="https://"]').count());const sizes=await education.locator('p,li').evaluateAll(elements=>elements.map(element=>parseFloat(getComputedStyle(element).fontSize)));assert.ok(sizes.length&&sizes.every(size=>size>=14));}
  check('All 48 actual limb muscles select through search and expose sourced educational cards at 14 px or larger');
  const components=limbsNodes.filter(node=>node.kind==='component');
  assert.equal(components.length,12);
  for(const node of components){await choose(node);const card=page.getByRole('region',{name:'Información muscular de '+node.name,exact:true});assert.match(await card.innerText(),/Componente de/);if(node.sourceId==='FMA45891'||node.sourceId==='FMA45892')assert.match(await card.innerText(),/fibular común/);}
  check('All 12 source heads retain component cards and short biceps innervation');
  for(const side of ['right','left']){const quad=byId.get('muscular:group:quadriceps:'+side);await choose(quad);await action('Aislar');assert.equal((await parts()).filter(p=>p.visible).length,4);await reset();const visible=await context(quad);assert.equal(visible.length,8);await reset();}
  check('Quadriceps remains four muscles with grouped ipsilateral bone context on both sides');
  for(const [query,node] of [['RECTO FEMORAL',rectus],['SARTORIO',sartorius],['BÍCEPS FEMORAL',posterior],[rectus.latin,rectus]]){assert.ok(query,'Documented search term');await structures();await page.getByRole('textbox',{name:'Buscar estructura anatómica'}).fill(query);await page.locator(`.atlas-search-result[data-node-id="${node.id}"]`).waitFor();const text=await page.locator(`.atlas-search-result[data-node-id="${node.id}"]`).innerText();assert.match(text,/Músculo/);assert.match(text,/Sistema muscular/);}
  check('Limbs Spanish uppercase, accents and documented Latin search keeps type/system/region labels');
  await choose(posterior);await clearSearch();await page.getByRole('button',{name:'Árbol anatómico',exact:true}).click();await page.getByRole('button',{name:'Expandir todo el árbol'}).click();const tree=page.getByRole('tree',{name:'Árbol anatómico'});await tree.getByRole('treeitem',{selected:true}).waitFor({state:'visible'});assert.ok(await tree.getByRole('treeitem').count()<nodes.length/2);await tree.focus();await page.keyboard.press('Home');assert.equal(await selectedName(),'Cuerpo humano');await page.keyboard.press('End');await tree.getByRole('treeitem',{selected:true}).waitFor({state:'visible'});check('Expanded limbs hierarchy remains virtualized with visible Home/End selection');
  for(const node of [rectus,sartorius,posterior,deep,muscle('gastrocnemius'),muscle('pronatorteres')]){await choose(node);for(const direction of ['anterior','posterior','left','right','superior','inferior'])await h.view(direction);await action('Aislar');const owned=descendants(node.id);assert.equal((await parts()).filter(part=>part.visible).length,ownedParts(node).length);assert.ok((await parts()).filter(part=>part.visible).every(part=>owned.has(part.id)));await action('Ocultar');assert.ok((await parts()).every(part=>!part.visible));await h.view('anterior');assert.ok((await parts()).every(part=>!part.visible),'Camera does not implicitly reveal hidden muscle');await action('Mostrar');assert.equal((await parts()).filter(part=>part.visible).length,ownedParts(node).length);await reset();}
  check('Thigh, leg and forearm muscles preserve selection/isolation/hiding across all six camera views');
  await choose(rectus);await action('Aislar');await h.view('anterior');await action('Deseleccionar');const box=await page.locator('.atlas-canvas canvas').boundingBox();let hit,hoverColors;
  for(const y of [.5,.4,.6,.3,.7,.2,.8]){for(const x of [.5,.4,.6,.3,.7,.2,.8]){await page.mouse.move(box.x+box.width*x,box.y+box.height*y);await wait(50);if(await page.locator('.atlas-canvas canvas').evaluate(canvas=>canvas.style.cursor==='pointer')){hoverColors=(await parts()).filter(part=>part.visible).map(part=>part.color);await page.mouse.click(box.x+box.width*x,box.y+box.height*y);const name=await selectedName();hit=ownedParts(rectus).find(node=>node.name===name);if(hit)break;}}if(hit)break;}
  assert.ok(hit,'Actual WebGL raycast selects the real rectus femoris mesh');await wait(200);assert.notDeepEqual((await parts()).filter(part=>part.visible).map(part=>part.color),hoverColors);check('Rectus femoris raycast, hover and cyan selection remain distinct',{id:hit.id});await reset();
  for(const node of [rectus,sartorius,posterior,deep,muscle('gastrocnemius'),muscle('pronatorteres')]){const visibleIds=await context(node);check('Curated muscle-bone context '+node.family,{visibleIds});await reset();}
  for(const direction of ['anterior','posterior','right']){await h.view(direction);for(const value of [100,75,50,25,10]){await opacity(value);const state=await parts();assert.ok(state.filter(part=>part.systemId==='muscular').every(part=>Math.abs(part.opacity-value/100)<1e-8&&part.transparent===(value<100)&&part.depthWrite===(value===100)));assert.ok(state.filter(part=>part.systemId==='skeletal').every(part=>part.opacity===1));}}
  check('100/75/50/25/10% limbs material states over opaque bone in anterior/posterior/lateral views');await reset();
  const rest=await atRest();
  for(const level of ['systems','regions','structures']){await explode(level,100);const first=positions(await parts());assert.notDeepEqual(first,rest);assert.equal((await h.metrics()).geometryBytes,initial.geometryBytes);if(level==='systems')for(const system of ['skeletal','muscular']){const values=(await parts()).filter(part=>part.systemId===system).map(part=>part.position.map((value,i)=>value-part.restPosition[i]));for(const offset of values)for(let axis=0;axis<3;axis++)assert.ok(Math.abs(offset[axis]-values[0][axis])<1e-12);}if(level==='regions')for(const side of ['right','left']){const values=(await parts()).filter(part=>{const n=byId.get(part.id);return n?.side===side&&n.regionId.includes(':leg-'+side);}).map(part=>part.position.map((value,i)=>value-part.restPosition[i]));assert.ok(values.length>20);for(const offset of values)for(let axis=0;axis<3;axis++)assert.ok(Math.abs(offset[axis]-values[0][axis])<1e-12,'Whole lower limb remains one block across hip/knee/ankle');}await explode(level,0);assert.deepEqual(await atRest(),rest);await explode(level,100);assert.deepEqual(positions(await parts()),first);await explode(level,0);}
  check('All explosion levels retain ownership, coherent limbs block, determinism and exact restoration');
  const target=limbsAssets.find(asset=>asset.id==='muscular:thigh-right');await layers();for(let cycle=0;cycle<3;cycle++){await assetInput(target).uncheck();await h.waitMeshes(totalMeshes-target.meshCount);assert.ok((await h.metrics()).geometryBytes<initial.geometryBytes);await assetInput(target).check();await h.waitMeshes(totalMeshes);assert.equal((await h.metrics()).geometryBytes,initial.geometryBytes);}check('Limbs unload/reload releases owned buffers without growth');
  const pattern='**/'+target.path.replace(/^\//,'');await page.route(pattern,async route=>{await new Promise(resolve=>setTimeout(resolve,350));await route.continue().catch(()=>{});});for(let cycle=0;cycle<5;cycle++){await assetInput(target).uncheck();await assetInput(target).check();}await h.waitMeshes(totalMeshes);await page.unroute(pattern);assert.equal((await h.metrics()).geometryBytes,initial.geometryBytes);assert.ok((await h.metrics()).renderGeometries<=initial.renderGeometries);check('Rapid limbs module cancellation/reload remains bounded');
  let allowed=false,attempts=0;await page.route(pattern,route=>{attempts++;return allowed?route.continue():route.abort('failed');});await page.goto(h.origin+'/med3d/anatomia/?qa=1',{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Reintentar regiones pendientes'}).waitFor({timeout:120000});await h.waitMeshes(totalMeshes-target.meshCount);assert.equal(attempts,1);const healthy=await h.metrics();allowed=true;await page.getByRole('button',{name:'Reintentar regiones pendientes'}).click();await h.waitMeshes(totalMeshes);assert.equal(attempts,2);assert.equal((await h.metrics()).geometryBytes,initial.geometryBytes);await page.unroute(pattern);check('Limbs network failure retains healthy anatomy until explicit retry',{attempts,retainedMeshes:healthy.meshCount});
  for(const [width,height] of [[1366,768],[1050,844],[900,1000],[390,844]]){await page.setViewportSize({width,height});await wait(400);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No overflow '+width);await layers();for(const asset of limbsAssets)assert.ok(await assetInput(asset).isVisible());await closePanels();await choose(posterior);await clearSearch();await page.getByRole('button',{name:'Árbol anatómico',exact:true}).click();await page.getByRole('tree',{name:'Árbol anatómico'}).getByRole('treeitem',{selected:true}).waitFor({state:'visible'});await closePanels();if(width===390){await page.getByRole('button',{name:'Inspección',exact:true}).click();assert.ok(await page.getByRole('region',{name:'Información muscular de '+posterior.name,exact:true}).isVisible());await closePanels();assert.ok((await page.locator('.atlas-canvas canvas').boundingBox()).height>height*.4);}check('Limbs tree/search/layers/card responsive '+width);}
  await page.setViewportSize({width:1366,height:768});for(const route of ['procedimientos','procedimientos/presion-arterial','procedimientos/signos-vitales','procedimientos/vendaje','procedimientos/inmovilizacion','primeros-auxilios','primeros-auxilios/rcp','primeros-auxilios/atragantamiento','primeros-auxilios/hemorragias','primeros-auxilios/quemaduras','primeros-auxilios/fracturas','primeros-auxilios/desmayos','primeros-auxilios/convulsiones','primeros-auxilios/botiquin']){const response=await page.goto(h.origin+'/med3d/'+route+'/',{waitUntil:'domcontentloaded'});assert.equal(response.status(),200);await page.locator('main h1').waitFor();const heading=(await page.locator('main h1').innerText()).trim();assert.ok(heading);assert.doesNotMatch(heading,/no encontrado|not found/i);}check('All existing procedure and first-aid routes remain readable');
}

async function captures(){
  await goto();
  for(const [direction,file] of [['anterior','01-cuerpo-anterior'],['posterior','02-cuerpo-posterior'],['right','03-lateral-derecho'],['left','04-lateral-izquierdo']]){await h.view(direction);await shot(file,'Available anatomy only; no complete muscular coverage claim.');}
  const region=(area,side='right')=>byId.get(area==='forearm'?`muscular:region:arm-${side}:forearm`:`muscular:region:leg-${side}:${area}`);
  for(const [area,division,direction,file] of [
    ['gluteal',null,'posterior','05-region-glutea'],['thigh','anterior','anterior','06-muslo-anterior'],
    ['thigh','medial','left','07-muslo-medial'],['thigh','posterior','posterior','08-muslo-posterior'],
    ['leg','anterior','anterior','09-pierna-anterior'],['leg','lateral','right','10-pierna-lateral'],
    ['leg','posterior','posterior','11-pantorrilla-posterior']]){
    await reset();const node=division?byId.get(region(area).id+':'+division):region(area);await choose(node);await h.view(direction);await action('Deseleccionar');await shot(file,'Regional focus retains all visible context; no automatic hiding.');
  }
  await reset();await choose(byId.get('muscular:group:quadriceps:right'));await h.view('anterior');await shot('12-cuadriceps-seleccionado','Four named muscles in one editorial group, not five muscles.');await action('Aislar');await shot('13-cuadriceps-aislado');
  await reset();await choose(byId.get(region('thigh').id+':posterior'));await action('Aislar');await h.view('posterior');await shot('14-muslo-posterior-aislado','Biceps femoris heads, semitendinosus and semimembranosus. Short biceps head does not cross the hip.');
  await reset();await choose(muscle('gastrocnemius'));await h.view('posterior');await shot('15-gastrocnemio');
  await reset();await choose(muscle('soleus'));await h.view('posterior');await shot('16-soleo-contextual','Deep to gastrocnemius; contextual occlusion is expected.');await action('Aislar');await shot('16b-soleo-aislado');
  for(const [division,direction,file] of [['anterior','anterior','17-antebrazo-anterior'],['posterior','posterior','18-antebrazo-posterior']]){await reset();await choose(byId.get(region('forearm').id+':'+division));await h.view(direction);await action('Deseleccionar');await shot(file);}
  await reset();await choose(muscle('tibialisposterior'));await action('Aislar');await h.view('posterior');await shot('19-tibial-posterior-aislado','Intrinsic hand/foot modules are deferred; this extra capture inspects the approved deep leg mesh.');
  await reset();await choose(muscle('supinator'));await action('Aislar');await h.view('right');await shot('20-supinador-aislado');
  await reset();await opacity(50);await h.view('anterior');await shot('21-muscular-50-oseo-100');
  await reset();await layers();await systemInput('skeletal').uncheck();await h.waitMeshes(muscleMeshes);await h.view('anterior');await shot('22-solo-muscular');await systemInput('skeletal').check();await systemInput('muscular').uncheck();await h.waitMeshes(boneMeshes);await shot('23-solo-oseo');
  for(const [level,file] of [['systems','24-exploded-sistemas'],['regions','25-exploded-regiones'],['structures','26-exploded-estructuras']]){await reset();if(level==='structures')await choose(region('thigh'));await h.view('anterior');await explode(level,100);await shot(file,'Educational bounded displacement; inspect retained ownership and overlaps.');}
  await reset();await context(muscle('rectusfemoris'));await h.view('anterior');await shot('27-contexto-recto-femoral','Coxal origin, patella insertion and tibial continuity through patellar ligament; no painted attachment masks.');
  await reset();await context(muscle('gastrocnemius'));await h.view('posterior');await shot('27b-contexto-gastrocnemio');
  await reset();await context(muscle('tibialisanterior'));await h.view('anterior');await shot('27c-contexto-tibial-anterior');
  await reset();await context(byId.get('muscular:group:quadriceps:right'));await h.view('anterior');await shot('27d-contexto-cuadriceps','Four muscles and explicit ipsilateral coxal, femur, patella and tibia.');
  for(const [width,height,file] of [[1366,768,'28-laptop-1366'],[1050,844,'28b-laptop-1050'],[900,1000,'29-tablet-900'],[390,844,'30-movil-390']]){await page.setViewportSize({width,height});await reset();await closePanels();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot(file,'CSS viewport; not a physical device performance measurement.');}
  await layers();await page.locator('[data-asset-id="muscular:thigh-right"]').scrollIntoViewIfNeeded();await shot('30b-movil-capas-inferiores');await page.locator('[data-asset-id="muscular:forearm-left"]').scrollIntoViewIfNeeded();await shot('30c-movil-capas-antebrazo');await closePanels();
  await choose(muscle('bicepsfemoris'));await clearSearch();await page.getByRole('button',{name:'Árbol anatómico',exact:true}).click();await page.getByRole('tree',{name:'Árbol anatómico'}).getByRole('treeitem',{selected:true}).waitFor({state:'visible'});await shot('30d-movil-arbol');await closePanels();
  await page.getByRole('button',{name:'Inspección',exact:true}).click();await shot('30e-movil-ficha');await page.getByRole('region',{name:'Información muscular de '+muscle('bicepsfemoris').name,exact:true}).getByRole('heading',{name:'Inervación',exact:true}).scrollIntoViewIfNeeded();await shot('30f-movil-inervacion');await closePanels();
  await page.setViewportSize({width:1440,height:900});
  for(const [area,direction] of [['thigh','anterior'],['leg','posterior'],['forearm','anterior']]){await reset();await choose(region(area));await h.view(direction);await action('Deseleccionar');for(const value of [100,75,50,25,10]){await opacity(value);await shot('opacity-'+area+'-'+String(value).padStart(3,'0'),`Muscle ${value}%, bone 100%; inspect bands, accumulation and depth sorting.`);}}
  for(const [family,direction] of [['gluteusminimus','right'],['vastusintermedius','anterior']]){await reset();await choose(muscle(family));await h.view(direction);await shot('deep-'+family+'-contextual','Source depth retained; camera never hides superficial neighbors.');await action('Aislar');await shot('deep-'+family+'-isolated');}
  for(const [area,direction] of [['leg','posterior'],['forearm','anterior']]){await reset();await choose(region(area));await h.view(direction);await explode('structures',100);await shot('exploded-'+area+'-structures','Bounded offsets may retain overlap; exact zero restoration is checked separately.');}
  report.humanReview='Every final PNG requires separate visual inspection; no clinical certification.';
}

const measured=async action=>{const start=performance.now();await action();return performance.now()-start;};
async function performanceQa(){
  await page.setViewportSize({width:1366,height:768});
  report.environment.limitations=['Software WebGL, not physical GPU performance.','Sequential configurations may benefit from earlier runtime initialization.','Geometry buffers are owned decoded CPU arrays, not GPU VRAM.','UI timings include browser automation and React acknowledgement.','No real mobile network, battery or thermal measurements.'];
  const configurations=[['A-skeletal','skeletal'],['B-phase3a-muscular','muscular',PILOT_ASSET_IDS],['C-phase3a-3b-muscular','muscular',PHASE3B_ASSET_IDS],['D-all-muscular','muscular'],['E-body-combined','skeletal,muscular']];
  for(const [name,systems,modules] of configurations){
    const requested=await goto(systems,modules);await page.waitForFunction(()=>Number(document.querySelector('.atlas-viewport')?.dataset.fullSystemMs)>0,null,{timeout:30000});const initial=await h.metrics();assert.equal(initial.meshCount,sum(requested,'meshCount'));assert.equal(initial.triangleCount,sum(requested,'triangles'));
    const record={modules:requested.map(asset=>asset.id),glbBytes:sum(requested,'bytes'),meshes:initial.meshCount,triangles:initial.triangleCount,geometryBuffersBytes:initial.geometryBytes,drawCalls:initial.drawCalls,firstGeometryMs:initial.firstGeometryMs,fullReadyMs:initial.fullSystemMs,initial,loadMarks:await page.evaluate(()=>performance.getEntriesByType('mark').filter(entry=>entry.name.startsWith('med3d:')).map(entry=>({name:entry.name,startTimeMs:entry.startTime}))),resources:await page.evaluate(()=>performance.getEntriesByType('resource').filter(entry=>entry.name.endsWith('.glb')).map(entry=>({name:entry.name.split('/').at(-1),durationMs:entry.duration,encodedBodyBytes:entry.encodedBodySize,transferBytes:entry.transferSize})))};
    const node=name.startsWith('A-')?h.catalog.nodes.find(node=>node.name==='Fémur izquierdo'):name.startsWith('B-')?byId.get('med3d:muscle:bicepsbrachii:right'):name.startsWith('C-')?byId.get('med3d:muscle:pectoralismajor:right'):muscle('rectusfemoris');
    record.searchMs=await measured(async()=>{await structures();await page.getByRole('textbox',{name:'Buscar estructura anatómica'}).fill(node.name);await page.locator(`.atlas-search-result[data-node-id="${node.id}"]`).waitFor();});await choose(node);
    const wanted=new Set([...descendants(node.id)]);record.isolateMs=await measured(async()=>{await action('Aislar',0);await page.waitForFunction(ids=>{const visible=window.__med3dAtlasScene().parts.filter(part=>part.visible);return visible.length>0&&visible.every(part=>ids.includes(part.id));},[...wanted]);});await wait(250);record.isolated=await h.metrics();await action('Ver conjunto');
    const level=name.startsWith('E-')?'systems':'structures';record.explosionFirstResponseMs=await measured(async()=>{await page.getByRole('combobox',{name:'Nivel de despiece'}).selectOption(level);await setSlider(page.getByRole('slider',{name:'Separación de piezas'}),100);await page.waitForFunction(()=>window.__med3dAtlasScene().parts.some(part=>part.position.some((value,i)=>value!==part.restPosition[i])));});await explode(level,0);
    const target=requested.find(asset=>asset.id===(name.startsWith('A-')?'skeletal:leg-left':name.startsWith('B-')?'muscular:upper-right':name.startsWith('C-')?'muscular:thorax-anterior':'muscular:thigh-right'));assert.ok(target);await layers();record.region=target.id;record.regionUnloadMs=await measured(async()=>{await assetInput(target).uncheck();await h.waitMeshes(initial.meshCount-target.meshCount);});record.afterRegionUnload=await h.metrics();record.regionReloadMs=await measured(async()=>{await assetInput(target).check();await h.waitMeshes(initial.meshCount);});record.afterRegionReload=await h.metrics();assert.equal(record.afterRegionReload.geometryBytes,initial.geometryBytes);
    const system=name.startsWith('A-')?'skeletal':'muscular',retained=name.startsWith('E-')?boneMeshes:0;record.systemUnloadMs=await measured(async()=>{await systemInput(system).uncheck();await h.waitMeshes(retained);});record.afterSystemUnload=await h.metrics();if(!retained)assert.equal(record.afterSystemUnload.geometryBytes,0);record.systemReloadMs=await measured(async()=>{await systemInput(system).check();await h.waitMeshes(initial.meshCount);});record.afterSystemReload=await h.metrics();assert.equal(record.afterSystemReload.geometryBytes,initial.geometryBytes);
    const cdp=await h.context.newCDPSession(page);await cdp.send('Performance.enable');record.browserMemory=Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.filter(metric=>['JSHeapUsedSize','JSHeapTotalSize','Nodes','Documents'].includes(metric.name)).map(metric=>[metric.name,metric.value]));await cdp.detach();record.detectedWebGL=await page.locator('.atlas-canvas canvas').evaluate(canvas=>{const gl=canvas.getContext('webgl2')||canvas.getContext('webgl'),ext=gl.getExtension('WEBGL_debug_renderer_info');return {renderer:gl.getParameter(ext?ext.UNMASKED_RENDERER_WEBGL:gl.RENDERER),vendor:gl.getParameter(ext?ext.UNMASKED_VENDOR_WEBGL:gl.VENDOR)};});report.measurements[name]=record;console.log('MEASURE',name,JSON.stringify(record));
  }
}

// Slow software WebGL hosts may need more wall time for the complete suite.
// This changes only the runner deadline, never an assertion or measured latency.
const suiteTimeoutMs=Number(process.env.QA_SUITE_TIMEOUT_MS||(mode==='functional'?1200000:mode==='captures'?900000:600000));
assert.ok(Number.isFinite(suiteTimeoutMs)&&suiteTimeoutMs>0,'QA_SUITE_TIMEOUT_MS must be a positive finite number');
report.environment.suiteTimeoutMs=suiteTimeoutMs;
try{await withinQaDeadline(async()=>{await ({functional,captures,performance:performanceQa}[mode])();assert.deepEqual(h.errors,[],'No unhandled browser errors');assert.deepEqual(h.badRequests,[],'No HTTP error responses');report.success=true;},suiteTimeoutMs,'Fase 3C '+mode);}
catch(error){report.success=false;report.error=error.stack;await page.screenshot({path:path.join(output,'failure.png'),fullPage:false,timeout:20000}).catch(error=>{report.failureScreenshotError=error.message;});throw error;}
finally{await writeFile(path.join(output,'limbs-'+mode+'.json'),JSON.stringify(report,null,2)+'\n');await h.close();}
