// Fase 3A browser evidence. Actual production WebGL, curated catalog IDs and
// user-facing actions; the read-only ?qa=1 bridge exposes rendered Three meshes.
import assert from 'node:assert/strict';
import {readFile, writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createHarness, project, setSlider, withinQaDeadline} from './browser-qa.mjs';

const mode=process.argv.find(arg=>['--functional','--captures','--performance'].includes(arg))?.slice(2)||'functional';
const h=await createHarness({output:process.env.QA_OUTPUT_DIR||path.join(project,'.qa-pilot',mode),viewport:{width:1440,height:900},reducedMotion:mode==='captures'?'reduce':'no-preference'});
const {page,output}=h;
const muscular=JSON.parse(await readFile(path.join(project,process.env.QA_SERVE_DIR||'dist','models/anatomy/muscular/catalog.json'),'utf8'));
const catalogs=[h.catalog,muscular],nodes=catalogs.flatMap(c=>c.nodes),assets=catalogs.flatMap(c=>c.assets);
const byId=new Map(nodes.map(n=>[n.id,n]));
const boneMeshes=h.expectedMeshes,muscleMeshes=muscular.coverage.meshes,totalMeshes=boneMeshes+muscleMeshes;
const countTriangles=list=>list.reduce((sum,a)=>sum+a.triangles,0);
const report={date:new Date().toISOString(),mode,source:'Local production build served over unthrottled loopback HTTP',environment:{browser:'Headless Chromium',renderer:'ANGLE SwiftShader software WebGL',physicalGpuTested:false,deviceScaleFactor:1},checks:[],captures:[],measurements:{},errors:h.errors,badRequests:h.badRequests};
const check=(name,values={})=>{report.checks.push({name,...values});console.log('PASS',name,JSON.stringify(values));};
const wait=ms=>page.waitForTimeout(ms);
const snapshot=()=>page.evaluate(()=>{
  if(typeof window.__med3dAtlasScene!=='function')throw new Error('Read-only renderer QA bridge is unavailable (?qa=1 required).');
  return window.__med3dAtlasScene();
});
const parts=async()=>[...(await snapshot()).parts].sort((a,b)=>a.id.localeCompare(b.id));
const selectedName=()=>page.locator('.atlas-detail-content h2').textContent();
async function openStructures(){const input=page.getByRole('textbox',{name:'Buscar estructura anatómica'});if(!await input.isVisible())await page.getByRole('button',{name:'Estructuras',exact:true}).click();}
async function clearSearch(){await openStructures();await page.getByRole('textbox',{name:'Buscar estructura anatómica'}).fill('');}
async function layers(){await clearSearch();await page.getByRole('button',{name:'Capas',exact:true}).click();}
const systemInput=id=>page.locator(`[data-system-id="${id}"] .atlas-layer-toggle input`);
const systemSlider=id=>page.locator(`[data-system-id="${id}"] .atlas-layer-opacity input`);
const assetInput=asset=>page.locator(`[data-system-id="${asset.systemId}"] [data-asset-id="${asset.id}"]`).getByRole('checkbox');
async function setSystems(skeletal,muscle){await layers();await systemInput('skeletal').setChecked(skeletal);await systemInput('muscular').setChecked(muscle);await h.waitMeshes((skeletal?boneMeshes:0)+(muscle?muscleMeshes:0));await wait(400);}
async function opacity(system,value){await layers();await setSlider(systemSlider(system),value);await wait(300);}
async function goto(systems='skeletal,muscular'){await page.goto(h.origin+'/med3d/anatomia/?qa=1&systems='+systems,{waitUntil:'domcontentloaded'});await h.waitMeshes((systems.includes('skeletal')?boneMeshes:0)+(systems.includes('muscular')?muscleMeshes:0));await wait(700);}
async function reset(){await page.getByRole('button',{name:'Restablecer atlas'}).click();await h.waitMeshes(totalMeshes);await wait(1100);}
async function choose(node){assert.ok(node,'Required curated catalog node exists');await openStructures();await page.getByRole('textbox',{name:'Buscar estructura anatómica'}).fill(node.name);await page.locator(`.atlas-search-result[data-node-id="${node.id}"]`).click();await page.waitForFunction(name=>document.querySelector('.atlas-detail-content h2')?.textContent===name,node.name);await wait(800);}
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function muscle(name,side='right'){
  const sideWord=side==='right'?'derech':'izquierd';
  const found=muscular.nodes.filter(n=>n.kind==='structure'&&(n.side===side||normalize(n.name).includes(sideWord))&&normalize(n.name).includes(normalize(name)));
  assert.equal(found.length,1,`Exactly one whole ${name} (${side})`);return found[0];
}
function region(name,side='right'){
  const found=muscular.nodes.filter(n=>n.kind==='region'&&(n.side===side||normalize(n.name).includes(side==='right'?'derech':'izquierd'))&&normalize(n.name).startsWith(normalize(name)+' ')&&!normalize(n.name).includes(' y '));
  assert.equal(found.length,1,`Exactly one ${name} region (${side})`);return found[0];
}
function descendants(id){const result=new Set([id]);for(const child of byId.get(id)?.children||[])for(const value of descendants(child))result.add(value);return result;}
const muscleLeaves=node=>{const ids=descendants(node.id);return muscular.nodes.filter(n=>ids.has(n.id)&&n.meshNames.length>0&&!n.children.some(child=>byId.get(child)?.meshNames.length));};
async function action(name,settle=400){const button=page.locator('.atlas-selection-actions').getByRole('button',{name,exact:true});if(!await button.isVisible()){const inspect=page.getByRole('button',{name:'Inspección',exact:true});if(await inspect.isVisible())await inspect.click();}await button.click();if(settle)await wait(settle);}
async function explode(level,value){await page.getByRole('combobox',{name:'Nivel de despiece'}).selectOption(level);await setSlider(page.getByRole('slider',{name:'Separación de piezas'}),value);await wait(100);await page.waitForFunction(()=>{const parts=window.__med3dAtlasScene().parts;return parts.length>0&&parts.every(p=>p.targetPosition&&p.position.every((v,i)=>v===p.targetPosition[i]));},null,{timeout:120000});}
const positionState=list=>list.map(p=>({id:p.id,position:p.position,restPosition:p.restPosition}));
async function assertAtRest(){const list=await parts();for(const part of list)assert.deepEqual(part.position,part.restPosition,`Exact rest transform: ${part.id}`);return positionState(list);}
async function shot(name,note=''){
  await page.mouse.move(10,10);await wait(200);await page.screenshot({path:path.join(output,name+'.png'),fullPage:false});
  report.captures.push({file:name+'.png',viewport:page.viewportSize(),selection:await selectedName(),note,metrics:await h.metrics(),scene:await snapshot()});console.log('CAPTURE',name);
}
async function closePanels(){for(const name of ['Cerrar estructuras','Cerrar inspección']){const close=page.getByRole('button',{name,exact:true});if(await close.isVisible())await close.click();}}
async function functional(){
  await goto();const initial=await h.metrics();assert.equal(muscleMeshes,26);assert.equal(muscular.nodes.filter(n=>n.kind==='structure').length,16);assert.equal(initial.triangleCount,countTriangles(assets));assert.equal(initial.loadedAssets,assets.length);check('Combined registered skeletal + 26-component, 16-muscle pilot loads',initial);
  report.environment.detectedWebGL=await page.locator('.atlas-canvas canvas').evaluate(canvas=>{const gl=canvas.getContext('webgl2')||canvas.getContext('webgl'),ext=gl.getExtension('WEBGL_debug_renderer_info');return {renderer:gl.getParameter(ext?ext.UNMASKED_RENDERER_WEBGL:gl.RENDERER),vendor:gl.getParameter(ext?ext.UNMASKED_VENDOR_WEBGL:gl.VENDOR)};});
  await setSystems(false,true);assert.equal((await h.metrics()).triangleCount,countTriangles(muscular.assets));const muscleOnly=await h.metrics();check('Skeletal layer unload retains complete muscular pilot',muscleOnly);
  const right=muscular.assets.find(a=>/right/.test(a.id)),left=muscular.assets.find(a=>/left/.test(a.id));assert.ok(right&&left);
  await assetInput(left).uncheck();await h.waitMeshes(right.meshCount);assert.equal((await h.metrics()).triangleCount,right.triangles);check('Right muscular module alone loads',{meshes:right.meshCount});
  await systemInput('muscular').uncheck();await h.waitMeshes(0);await systemInput('muscular').check();await h.waitMeshes(right.meshCount);assert.ok(!await assetInput(left).isChecked());check('System activation restores its chosen module subset');
  await assetInput(right).uncheck();await h.waitMeshes(0);assert.equal((await h.metrics()).geometryBytes,0);
  await assetInput(left).check();await h.waitMeshes(left.meshCount);assert.equal((await h.metrics()).triangleCount,left.triangles);check('Left muscular module alone loads',{meshes:left.meshCount});
  await assetInput(right).check();await h.waitMeshes(muscleMeshes);assert.equal((await h.metrics()).geometryBytes,muscleOnly.geometryBytes);check('Both muscular modules reload without geometry growth');
  await setSystems(true,false);assert.equal((await h.metrics()).triangleCount,h.expectedTriangles);check('Muscular layer unload preserves skeleton');await setSystems(true,true);
  for(const value of [100,75,50,25,10]){await opacity('muscular',value);const state=await parts();assert.ok(state.filter(p=>p.systemId==='muscular').every(p=>Math.abs(p.opacity-value/100)<1e-8));assert.ok(state.filter(p=>p.systemId==='skeletal').every(p=>p.opacity===1));assert.ok(state.filter(p=>p.systemId==='muscular').every(p=>p.transparent===(value<100)&&p.depthWrite===(value===100)));}
  await opacity('skeletal',40);await opacity('muscular',75);let state=await parts();assert.ok(state.filter(p=>p.systemId==='skeletal').every(p=>p.opacity===.4));assert.ok(state.filter(p=>p.systemId==='muscular').every(p=>p.opacity===.75));
  await setSystems(true,false);await setSystems(true,true);state=await parts();assert.ok(state.filter(p=>p.systemId==='muscular').every(p=>p.opacity===.75));check('Independent opacities and depth-write states persist across system unload');await reset();
  for(const query of ['deltoides','bíceps','bíceps braquial','tríceps','braquial','supraespinoso','infraespinoso','subescapular','redondo menor','húmero','escápula','clavícula','corazón','pulmones','encéfalo']){
    await openStructures();await page.getByRole('textbox',{name:'Buscar estructura anatómica'}).fill(query);await page.waitForFunction(query=>{const clean=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return [...document.querySelectorAll('.atlas-search-result span')].some(e=>clean(e.textContent).includes(clean(query)));},query);assert.ok(await page.locator('.atlas-search-result').count()>0,query);
    if(['deltoides','bíceps braquial'].includes(query)){const text=await page.locator('.atlas-global-results').innerText();assert.match(text,/Sistema muscular/);assert.match(text,/Músculo/);assert.match(text,/Componente/);assert.match(text,/Hombro|Brazo|brazo/);}
  }check('Global accent-aware search finds all required muscles, bones and legacy organs');
  await clearSearch();await page.getByRole('button',{name:'Árbol anatómico',exact:true}).click();await page.getByRole('button',{name:'Expandir todo el árbol'}).click();const tree=page.getByRole('tree',{name:'Árbol anatómico'});assert.ok(await tree.getByRole('treeitem').count()<nodes.length/2);await tree.focus();await page.keyboard.press('Home');assert.equal(await selectedName(),'Cuerpo humano');await page.keyboard.press('ArrowDown');assert.equal(await selectedName(),'Sistema óseo');await page.keyboard.press('End');await tree.getByRole('treeitem',{selected:true}).waitFor({state:'visible',timeout:20000});assert.ok(await tree.getByRole('treeitem',{selected:true}).isVisible());check('Neutral body root and virtualized multisystem keyboard tree');
  const deltoid=muscle('deltoides'),biceps=muscle('bíceps braquial');await choose(deltoid);
  const education=page.getByRole('region',{name:'Información muscular de '+deltoid.name,exact:true});for(const heading of ['Origen','Inserción','Inervación'])assert.ok(await education.getByRole('heading',{name:heading,exact:true}).count()>0);assert.ok(await education.locator('a[href^="https://"]').count()>0);const fontSizes=await education.locator('p,li').evaluateAll(elements=>elements.map(e=>parseFloat(getComputedStyle(e).fontSize)));assert.ok(fontSizes.length&&fontSizes.every(size=>size>=14),'Muscular educational body must be at least 14 px');check('Specialized muscle card includes curated attachment and innervation text',{minimumFontPx:Math.min(...fontSizes)});
  await action('Aislar');const deltoidIds=descendants(deltoid.id);state=await parts();assert.equal(state.filter(p=>p.visible).length,3);assert.ok(state.filter(p=>p.visible).every(p=>deltoidIds.has(p.id)));await action('Ocultar');await h.waitDraws(0);await action('Mostrar');await h.waitDraws(3);check('Whole deltoid isolation, hide and reveal preserves 3 component ownership');
  await action('Deseleccionar');const box=await page.locator('.atlas-canvas canvas').boundingBox();let selectedComponent=null,hoverColor=null;
  for(const y of [.5,.4,.6,.3,.7,.2,.8]){for(const x of [.5,.4,.6,.3,.7]){await page.mouse.move(box.x+box.width*x,box.y+box.height*y);await wait(40);if(await page.locator('.atlas-canvas canvas').evaluate(c=>c.style.cursor==='pointer')){hoverColor=(await parts()).filter(p=>p.visible).map(p=>p.color);await page.mouse.click(box.x+box.width*x,box.y+box.height*y);const name=await selectedName();selectedComponent=muscleLeaves(deltoid).find(n=>n.name===name);if(selectedComponent)break;}}if(selectedComponent)break;}
  assert.ok(selectedComponent,'Actual canvas raycast must select one deltoid component');await wait(150);const selectedColors=(await parts()).filter(p=>p.visible).map(p=>p.color);assert.notDeepEqual(selectedColors,hoverColor,'Hover must differ from selected appearance');check('Actual raycast selects a component, with distinct hover and selection',{id:selectedComponent.id});await reset();
  for(const name of ['deltoides','bíceps braquial','tríceps braquial','supraespinoso','infraespinoso','redondo menor','subescapular']){await choose(muscle(name));for(const direction of ['anterior','posterior','left','right','superior','inferior'])await h.view(direction);}check('Six camera views execute for superficial muscles and rotator cuff; occlusion remains explicit');
  await choose(biceps);const context=page.getByRole('button',{name:'Mostrar contexto',exact:true});await context.click();await wait(900);state=await parts();const visible=state.filter(p=>p.visible);assert.ok(visible.some(p=>p.systemId==='muscular')&&visible.some(p=>p.systemId==='skeletal'));assert.ok(visible.length<totalMeshes);assert.ok(visible.filter(p=>p.systemId==='muscular').every(p=>descendants(biceps.id).has(p.id)));check('Explicit curated biceps context shows muscle plus related bones',{visibleIds:visible.map(p=>p.id)});await reset();
  await choose(biceps);await action('Aislar');await layers();await systemInput('muscular').uncheck();await h.waitMeshes(boneMeshes);await action('Ver conjunto');await h.waitMeshes(boneMeshes);assert.ok(!await systemInput('muscular').isChecked(),'Leaving isolation must preserve an explicitly disabled muscular layer');state=await parts();assert.equal(state.filter(p=>p.visible&&p.systemId==='skeletal').length,boneMeshes);assert.equal(state.filter(p=>p.systemId==='muscular').length,0);check('Leaving muscle isolation preserves a disabled muscular layer and restores visible bones');await reset();
  await choose(biceps);await h.view('anterior');const beforeHide=positionState(await parts());await action('Ocultar');const beforeHiddenView=(await snapshot()).camera;await h.view('posterior');await page.waitForFunction(()=>{const camera=window.__med3dAtlasScene().camera;const delta=camera.position.map((v,i)=>v-camera.target[i]);return delta[2]<0&&Math.abs(delta[0])<Math.abs(delta[2])*.001&&Math.abs(delta[1])<Math.abs(delta[2])*.001;},null,{timeout:120000});assert.notDeepEqual((await snapshot()).camera.position,beforeHiddenView.position,'View request on hidden selection must move camera');assert.ok((await parts()).filter(p=>descendants(biceps.id).has(p.id)).every(p=>!p.visible));await action('Mostrar');assert.ok((await parts()).filter(p=>descendants(biceps.id).has(p.id)).every(p=>p.visible));assert.deepEqual(positionState(await parts()),beforeHide,'Hide, camera and reveal actions preserve mesh transforms');check('Hidden muscle accepts posterior camera requests without implicit reveal or mesh transform changes');await reset();
  const rest=await assertAtRest();
  for(const level of ['systems','regions','structures']){await explode(level,100);const first=positionState(await parts());assert.notDeepEqual(first,rest,level+' must change actual mesh positions');assert.equal((await h.metrics()).geometryBytes,initial.geometryBytes);
    if(level==='systems'){for(const system of ['skeletal','muscular']){const offsets=(await parts()).filter(p=>p.systemId===system).map(p=>p.position.map((x,i)=>x-p.restPosition[i]));for(const offset of offsets)for(let i=0;i<3;i++)assert.ok(Math.abs(offset[i]-offsets[0][i])<1e-12,'A system stays one coherent presentation block');}}
    await explode(level,0);assert.deepEqual(await assertAtRest(),rest);await explode(level,100);assert.deepEqual(positionState(await parts()),first,'Deterministic repeated '+level+' position');await explode(level,0);
  }check('Three explosion levels are deterministic and return exactly to original mesh positions');
  await choose(biceps);await explode('structures',100);const bicepsParts=(await parts()).filter(p=>descendants(biceps.id).has(p.id));assert.equal(bicepsParts.length,2);assert.notDeepEqual(bicepsParts[0].position.map((x,i)=>x-bicepsParts[0].restPosition[i]),bicepsParts[1].position.map((x,i)=>x-bicepsParts[1].restPosition[i]));check('Biceps two heads separate distinctly as components');await reset();
  await layers();for(let cycle=0;cycle<3;cycle++){await assetInput(right).uncheck();await h.waitMeshes(totalMeshes-right.meshCount);assert.ok((await h.metrics()).geometryBytes<initial.geometryBytes);await assetInput(right).check();await h.waitMeshes(totalMeshes);assert.equal((await h.metrics()).geometryBytes,initial.geometryBytes);}check('Muscular module unload/reload cycles release buffers and remain bounded');
  const delayedPattern='**/'+right.path.replace(/^\//,'');await page.route(delayedPattern,async route=>{await new Promise(resolve=>setTimeout(resolve,350));await route.continue().catch(()=>{});});
  for(let cycle=0;cycle<5;cycle++){await systemInput('muscular').uncheck();await systemInput('muscular').check();}await h.waitMeshes(totalMeshes);await page.unroute(delayedPattern);assert.equal((await h.metrics()).geometryBytes,initial.geometryBytes);assert.ok((await h.metrics()).renderGeometries<=initial.renderGeometries);check('Rapid muscular layer changes leave no unexpected CPU or renderer geometry growth');
  let allowed=false,attempts=0;await page.route(delayedPattern,route=>{attempts++;return allowed?route.continue():route.abort('failed');});await page.goto(h.origin+'/med3d/anatomia/?qa=1',{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Reintentar regiones pendientes'}).waitFor({timeout:120000});await h.waitMeshes(totalMeshes-right.meshCount);assert.equal(attempts,1);allowed=true;await page.getByRole('button',{name:'Reintentar regiones pendientes'}).click();await h.waitMeshes(totalMeshes);assert.equal(attempts,2);assert.equal((await h.metrics()).geometryBytes,initial.geometryBytes);await page.unroute(delayedPattern);check('Partial muscular network failure retains healthy modules and recovers only on explicit retry',{attempts});
  for(const [width,height] of [[1366,768],[1050,844],[900,1000],[390,844]]){await page.setViewportSize({width,height});await wait(350);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No overflow '+width);await layers();assert.ok(await systemInput('skeletal').isVisible()&&await systemInput('muscular').isVisible());await closePanels();if(width===390){await choose(biceps);await clearSearch();await page.getByRole('button',{name:'Árbol anatómico',exact:true}).click();await page.getByRole('tree',{name:'Árbol anatómico'}).getByRole('treeitem',{selected:true}).waitFor({state:'visible',timeout:20000});await closePanels();await openStructures();await page.getByRole('tree',{name:'Árbol anatómico'}).getByRole('treeitem',{selected:true}).waitFor({state:'visible',timeout:20000});assert.equal(await selectedName(),biceps.name);check('Reopened mobile tree retains its selected muscle without manual scrolling');await closePanels();const canvas=await page.locator('.atlas-canvas canvas').boundingBox();assert.ok(canvas.height>height*.4,'Mobile model remains a substantial part of viewport');assert.ok(!await page.locator('.atlas-sidebar').evaluate(e=>e.classList.contains('is-open')));}check('Responsive two-system panels '+width);}
  // Existing browser-qa independently verifies skeletal interactions and all 3
  // legacy organs. Keep these explicit pilot route checks to catch routing drift.
  await page.setViewportSize({width:1366,height:768});for(const organ of ['heart','lungs','brain']){await page.goto(h.origin+'/med3d/anatomia/?organ='+organ,{waitUntil:'domcontentloaded'});await page.locator('.atlas-canvas canvas').waitFor({state:'visible'});await page.waitForFunction(organ=>performance.getEntriesByType('resource').some(e=>e.name.endsWith('/models/'+organ+'.glb'))&&window.__atlasQa.draws>0,organ,{timeout:120000});await page.getByRole('progressbar',{name:'Descarga del modelo'}).waitFor({state:'detached',timeout:120000});assert.equal(await page.getByRole('alert').count(),0);check('Legacy '+organ+' still renders actual WebGL');}
}

async function captures(){
  await goto();await h.view('anterior');await shot('01-anterior-oseo-muscular','Both systems opaque. Inspect bilateral registration and limited shoulder/arm coverage.');await h.view('posterior');await shot('02-posterior-oseo-muscular');await h.view('right');await shot('03-lateral-derecho','Anatomical right of specimen.');await h.view('left');await shot('04-lateral-izquierdo','Anatomical left of specimen.');
  for(const [name,side,file] of [['hombro','right','05-hombro-derecho'],['hombro','left','06-hombro-izquierdo'],['brazo','right','07-brazo-derecho'],['brazo','left','08-brazo-izquierdo']]){await reset();await choose(region(name,side));await h.view('anterior');await shot(file,'Focus on curated muscular region, retaining opaque skeletal context.');}
  await reset();await choose(muscle('deltoides'));await h.view('anterior');await shot('09-deltoides-seleccionado');await action('Aislar');await shot('10-deltoides-aislado','Explicit isolation reveals the three original portions.');
  await reset();await choose(muscle('bíceps braquial'));await h.view('anterior');await shot('11-biceps-seleccionado');await action('Aislar');await shot('12-biceps-aislado','Explicit isolation, both original heads retained.');
  await reset();await choose(muscle('tríceps braquial'));await h.view('posterior');await shot('13-triceps');
  await reset();await choose(region('hombro'));await h.view('posterior');await shot('14-manguito-rotador-posterior','Opaque deltoid can occlude parts of cuff; this is contextual, not proof of every deep surface.');
  await clearSearch();await page.getByRole('button',{name:'Árbol anatómico',exact:true}).click();await page.getByRole('button',{name:'Expandir todo el árbol'}).click();await page.getByRole('tree',{name:'Árbol anatómico'}).getByRole('treeitem',{selected:true}).waitFor({state:'visible',timeout:20000});await page.getByRole('button',{name:'Ocultar '+muscle('deltoides').name,exact:true}).click();await wait(500);const cuffState=await parts();assert.ok(cuffState.filter(p=>descendants(muscle('deltoides').id).has(p.id)).every(p=>!p.visible));assert.ok(['supraespinoso','infraespinoso','redondo menor'].every(name=>cuffState.some(p=>p.id===muscle(name).id&&p.visible)));await shot('14b-manguito-sin-deltoides','Right deltoid explicitly hidden using its tree visibility button. Posterior cuff remains visible in skeletal context; no source geometry moved.');
  await reset();await choose(muscle('subescapular'));await h.view('anterior');await shot('15-subescapular','Contextual view; documented deep anatomy may be occluded.');await action('Aislar');await shot('15b-subescapular-aislado','Voluntary explicit isolation exposes the source mesh without claiming to solve contextual occlusion.');
  await reset();await choose(region('hombro'));await h.view('anterior');await opacity('muscular',50);await shot('16-muscular-50-oseo-100','Standard alpha blending, transparent muscles do not write depth.');
  await reset();await setSystems(false,true);await h.view('anterior');await shot('17-solo-musculos','Only bilateral pilot; this is not a complete muscular body.');await setSystems(true,false);await h.view('anterior');await shot('18-solo-huesos','Skeletal reference retains seven pending bones.');
  await reset();await h.view('anterior');await explode('systems',100);await shot('19-exploded-sistemas','Presentation offsets only; anatomical source registration remains unchanged.');await reset();await choose(region('hombro'));await h.view('anterior');await explode('regions',100);await shot('20-exploded-regiones');await reset();await choose(muscle('deltoides'));await action('Aislar');await h.view('anterior');await explode('structures',100);await shot('21-exploded-estructuras','Three deltoid portions explicitly isolated.');
  for(const name of ['bíceps braquial','tríceps braquial']){await reset();await choose(muscle(name));await action('Aislar');await h.view(name.startsWith('trí')?'posterior':'anterior');await explode('structures',100);await shot(name.startsWith('trí')?'21c-triceps-componentes':'21b-biceps-componentes');}
  for(const [width,height,file] of [[1366,768,'22-laptop-1366'],[1050,844,'22b-laptop-1050'],[900,1000,'23-tablet-900'],[390,844,'24-movil-390']]){await page.setViewportSize({width,height});await reset();await closePanels();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot(file,'CSS viewport profile; no physical device GPU claim.');}
  await layers();await shot('24b-movil-capas','Two systems shown in a voluntarily opened mobile panel.');await closePanels();await choose(muscle('bíceps braquial'));await page.getByRole('button',{name:'Inspección',exact:true}).click();await shot('24c-movil-ficha');await closePanels();
  await page.setViewportSize({width:1440,height:900});await reset();await choose(region('hombro'));await h.view('anterior');await action('Deseleccionar');for(const value of [100,75,50,25,10]){await opacity('muscular',value);await shot('opacity-'+String(value).padStart(3,'0'),`Muscular ${value}%, skeletal 100%. Inspect sorting, interpenetration, selection and bone visibility.`);}
  await choose(muscle('bíceps braquial'));await opacity('muscular',50);await shot('opacity-050-selected','Selected biceps remains distinct at muscle 50%, skeletal 100%.');
  await reset();await choose(muscle('bíceps braquial'));await page.getByRole('button',{name:'Mostrar contexto',exact:true}).click();await h.view('anterior');await shot('25-biceps-contexto','Explicit curated relationships, never proximity-generated attachment coordinates.');
  report.humanReview='Required separately; generating files does not assert anatomical approval.';
}

const measured=async action=>{const start=performance.now();await action();return performance.now()-start;};
async function performanceQa(){
  await page.setViewportSize({width:1366,height:768});report.measurements.operationTimingDefinition='UI event to acknowledged actual renderer/DOM state; includes automation transport and React work. Explosion timing ends at the first changed mesh position, not animation completion. Geometry bytes are decoded owned buffers, not GPU VRAM. No physical GPU, phone thermal or real network performance is inferred.';
  for(const [name,systems] of [['skeletal','skeletal'],['muscular','muscular'],['combined','skeletal,muscular']]){
    await goto(systems);await page.waitForFunction(()=>Number(document.querySelector('.atlas-viewport')?.dataset.fullSystemMs)>0,null,{timeout:30000});const initial=await h.metrics();
    const modelAssets=assets.filter(a=>systems.includes(a.systemId));const record={glbBytes:modelAssets.reduce((s,a)=>s+a.bytes,0),meshes:initial.meshCount,triangles:initial.triangleCount,geometryBuffersBytes:initial.geometryBytes,drawCalls:initial.drawCalls,firstGeometryMs:initial.firstGeometryMs,fullReadyMs:initial.fullSystemMs,initial,loadMarks:await page.evaluate(()=>performance.getEntriesByType('mark').filter(e=>e.name.startsWith('med3d:')).map(e=>({name:e.name,startTimeMs:e.startTime}))),resources:await page.evaluate(()=>performance.getEntriesByType('resource').filter(e=>e.name.endsWith('.glb')).map(e=>({name:e.name.split('/').at(-1),durationMs:e.duration,encodedBodyBytes:e.encodedBodySize,transferBytes:e.transferSize})))};
    const node=systems==='skeletal'?byId.get('bp3d:FMA24474')||h.catalog.nodes.find(n=>n.name==='Fémur izquierdo'):muscle('bíceps braquial');
    record.searchMs=await measured(async()=>{await openStructures();await page.getByRole('textbox',{name:'Buscar estructura anatómica'}).fill(node.name);await page.locator(`.atlas-search-result[data-node-id="${node.id}"]`).waitFor();});await choose(node);
    record.isolateMs=await measured(async()=>{await action('Aislar',0);await page.waitForFunction(()=>window.__med3dAtlasScene().parts.filter(p=>p.visible).length<=3);});record.isolated=await h.metrics();await action('Ver conjunto');
    const level=name==='combined'?'systems':'structures';record.explosionFirstResponseMs=await measured(async()=>{await page.getByRole('combobox',{name:'Nivel de despiece'}).selectOption(level);await setSlider(page.getByRole('slider',{name:'Separación de piezas'}),100);await page.waitForFunction(()=>window.__med3dAtlasScene().parts.some(p=>p.position.some((v,i)=>v!==p.restPosition[i])));});await explode(level,0);
    await layers();const system=name==='skeletal'?'skeletal':'muscular',retained=name==='combined'?boneMeshes:0;record.layerUnloadMs=await measured(async()=>{await systemInput(system).uncheck();await h.waitMeshes(retained);});record.afterUnload=await h.metrics();record.layerReloadMs=await measured(async()=>{await systemInput(system).check();await h.waitMeshes(initial.meshCount);});record.afterReload=await h.metrics();assert.equal(record.afterReload.geometryBytes,initial.geometryBytes);
    const cdp=await h.context.newCDPSession(page);await cdp.send('Performance.enable');record.browserMemory=Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.filter(m=>['JSHeapUsedSize','JSHeapTotalSize','Nodes','Documents'].includes(m.name)).map(m=>[m.name,m.value]));await cdp.detach();
    record.detectedWebGL=await page.locator('.atlas-canvas canvas').evaluate(canvas=>{const gl=canvas.getContext('webgl2')||canvas.getContext('webgl'),ext=gl.getExtension('WEBGL_debug_renderer_info');return {renderer:gl.getParameter(ext?ext.UNMASKED_RENDERER_WEBGL:gl.RENDERER),vendor:gl.getParameter(ext?ext.UNMASKED_VENDOR_WEBGL:gl.VENDOR)};});report.measurements[name]=record;console.log('MEASURE',name,JSON.stringify(record));
  }
}

try{await withinQaDeadline(async()=>{await ({functional,captures,performance:performanceQa}[mode])();assert.deepEqual(h.errors,[],'No unhandled browser errors');assert.deepEqual(h.badRequests,[],'No HTTP error responses');report.success=true;},mode==='functional'?900000:mode==='captures'?600000:300000,'Fase 3A '+mode);}
catch(error){report.success=false;report.error=error.stack;report.failureUi=await page.evaluate(()=>{const tree=document.querySelector('[role=tree]');return {selection:document.querySelector('.atlas-detail-content h2')?.textContent,tree:tree?{scrollTop:tree.scrollTop,scrollHeight:tree.scrollHeight,clientHeight:tree.clientHeight,rows:[...tree.querySelectorAll('[role=treeitem]')].map(row=>({id:row.id,selected:row.getAttribute('aria-selected'),text:row.textContent}))}:null};}).catch(()=>null);await page.screenshot({path:path.join(output,'failure.png'),fullPage:false,timeout:20000}).catch(error=>{report.failureScreenshotError=error.message;});throw error;}
finally{await writeFile(path.join(output,'pilot-'+mode+'.json'),JSON.stringify(report,null,2)+'\n');await h.close();}
