import SiteLink from "../../components/SiteLink";
import { ArrowRight, ArrowUpRight, Cube, Stack, Code, TreeStructure, Gauge, CheckCircle } from '@phosphor-icons/react';
import './about.css';

const sections = [
  { title: 'Identidad y propósito', body: 'MED3D es el nombre provisional de una plataforma educativa de anatomía, procedimientos y primeros auxilios. Una interfaz en español prioriza la claridad, la orientación espacial y el aprendizaje por pasos.', tags: ['Educación', 'Español', 'Nombre provisional'] },
  { title: 'Tres áreas de aprendizaje', body: 'Explorar reúne el atlas anatómico; observar organiza los procedimientos; responder presenta guías de primeros auxilios para adultos. Cada área comparte navegación y criterios visuales, con controles adaptados a su tarea.', tags: ['Explorar', 'Observar', 'Responder'] },
  { title: 'Navegación y rutas', body: 'Inicio, anatomía, catálogo y detalle de procedimientos, catálogo y detalle de primeros auxilios, alcance del proyecto y arquitectura. Las páginas de detalle mantienen una URL propia para poder consultarlas directamente.', tags: ['/', '/anatomia', '/procedimientos/:id', '/primeros-auxilios/:id'] },
  { title: 'Inicio editorial', body: 'Una portada anatómica, una propuesta de valor breve y accesos visibles a las tres áreas. Las ilustraciones acompañan a la navegación; las experiencias interactivas se abren en su propia página.', tags: ['Portada', 'Accesos directos', 'Diseño adaptable'] },
  { title: 'Atlas anatómico interactivo', body: 'Visor 3D con órbita y zoom, árbol de estructuras, búsqueda, selección por raycasting y ficha informativa. Las capas, la visibilidad, el aislamiento y la separación de órganos permiten estudiar relaciones espaciales.', tags: ['Capas', 'Selección', 'Ficha de estructura'] },
  { title: 'Escenas de procedimientos', body: 'Cada escena dispone de una línea de tiempo y una secuencia de pasos. El control de reproducción sincroniza la representación, el texto y las vistas de cámara. La primera escena muestra fundamentos de medición de la presión arterial.', tags: ['Tiempo maestro', 'Cámara', 'Pasos'] },
  { title: 'Primeros auxilios', body: 'Tarjetas por situación con alcance, pasos iniciales y referencias. La RCP en adultos tiene una escena esquemática. Las guías señalan cuándo contactar con emergencias y no sustituyen la capacitación presencial.', tags: ['Adultos', 'Guías', 'RCP esquemática'] },
  { title: 'Base tecnológica', body: 'React 19 y TypeScript para la interfaz; TanStack Router para rutas de la aplicación estática; Vite para construcción; GitHub Pages para publicación. Three.js, React Three Fiber y Drei resuelven el visor; El estado es local en esta versión; Zustand queda previsto para coordinar múltiples sistemas.', tags: ['React 19', 'TypeScript', 'Three.js', 'Estado modular'] },
  { title: 'Organización modular', body: 'Las rutas componen funciones de producto independientes: anatomy, learning, about y home. Componentes compartidos y datos se separan de la lógica de carga, la configuración y las escenas. La división permite ampliar el atlas sin reescribir la navegación.', tags: ['routes', 'features', 'components', 'data'] },
  { title: 'Manifiesto anatómico', body: 'Cada estructura recibe un identificador estable, nombre visible y latino, sistema y región, recurso GLB y nodos asociados. El registro incorpora transformaciones iniciales, vector de separación, descripción, fuente, autoría y licencia.', tags: ['ID estable', 'GLB', 'Metadatos', 'Atribución'] },
  { title: 'Carga y gestión de modelos', body: 'El atlas carga recursos por órgano o sistema y presenta estados de espera y error. Los cuatro archivos utilizan Meshopt y suman 6,6 MB. KTX2 y niveles de detalle se incorporarán si las mediciones justifican su uso.', tags: ['Carga diferida', 'Recuperación', 'Meshopt'] },
  { title: 'Separación de estructuras', body: 'El despiece parte siempre de la transformación original. Un valor común, suavizado y reversible, desplaza cada órgano sobre un vector definido. La jerarquía cuerpo → sistema → órgano conserva la agrupación y evita acumular desplazamientos.', tags: ['Transformación base', 'Reversible', 'Jerarquía'] },
  { title: 'Animación y autoría visual', body: 'Un reloj maestro gobierna movimientos y pasos. Esta versión utiliza maniquíes y animación programática de carácter esquemático; los futuros rigs requerirán revisión. Higgsfield se utiliza para recursos visuales de portada y tarjetas, creación de ilustraciones.', tags: ['Línea de tiempo', 'Maniquí esquemático', 'Higgsfield'] },
  { title: 'Rendimiento y accesibilidad', body: 'Objetivos de ingeniería: renderizado bajo demanda donde sea posible, densidad de píxel limitada a 1,5, liberación de recursos y cancelación de tareas obsoletas. Controles de teclado, foco visible, estados de carga y texto alternativo acompañan el contenido 3D.', tags: ['Objetivos, no mediciones', 'DPR ≤ 1,5', 'Teclado'] },
  { title: 'Evolución y criterios de calidad', body: 'Primero, consolidar tres órganos y una envolvente de piel orientativa. Después, ampliar sistemas con trazabilidad de recursos y revisión anatómica; incorporar escenas revisadas, evaluación de aprendizaje y mediciones de rendimiento en equipos reales.', tags: ['Cobertura gradual', 'Revisión experta', 'Medición'] },
];

export default function ArchitecturePage() {
  return (
    <main className="architecture-page">
      <div className="architecture-page-inner">
        <div className="about-breadcrumb"><SiteLink href="/">Inicio</SiteLink><span>/</span><span>Arquitectura</span></div>
        <header className="architecture-hero"><p className="about-eyebrow">DISEÑO DEL PRODUCTO</p><h1>Una experiencia clara.<br /><span>Una base extensible.</span></h1><p>La arquitectura de MED3D conecta contenido, modelos y aprendizaje. Esta es la propuesta de producto y el camino de evolución de su primera versión.</p><div className="architecture-header-meta"><span><Code size={16} /> React + TypeScript</span><span><Cube size={16} /> Anatomía en 3D</span><span><CheckCircle size={16} /> Alcance documentado</span></div></header>

        <section className="architecture-overview" aria-label="Relación entre experiencia, contenido y plataforma">
          <div className="architecture-layer"><span className="architecture-layer-icon"><TreeStructure size={24} /></span><p>EXPERIENCIA</p><div><span>Explorar</span><span>Observar</span><span>Responder</span></div><small>Atlas, escenas y guías conectadas por una misma navegación.</small></div>
          <div className="architecture-layer"><span className="architecture-layer-icon"><Stack size={24} /></span><p>CONTENIDO</p><div><span>Manifiesto</span><span>Modelos GLB</span><span>Secuencias</span></div><small>Identificadores, fuentes y recursos con responsabilidades separadas.</small></div>
          <div className="architecture-layer"><span className="architecture-layer-icon"><Code size={24} /></span><p>PLATAFORMA</p><div><span>React</span><span>Three.js</span><span>Cloudflare</span></div><small>Interfaz adaptable, escenas en el navegador y publicación web.</small></div>
        </section>

        <div className="architecture-content">
          <aside className="architecture-index" aria-label="Índice de arquitectura"><p className="about-eyebrow">15 DECISIONES</p><nav>{sections.map((section, index) => <SiteLink href={'#decision-' + (index + 1)} key={section.title}><span>{String(index + 1).padStart(2, '0')}</span>{section.title}</SiteLink>)}</nav></aside>
          <div className="architecture-decisions">{sections.map((section, index) => <section className="architecture-decision" id={'decision-' + (index + 1)} key={section.title}><div className="architecture-decision-number">{String(index + 1).padStart(2, '0')}</div><div><h2>{section.title}</h2><p>{section.body}</p><div className="architecture-tags">{section.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div></section>)}</div>
        </div>

        <section className="architecture-roadmap" aria-labelledby="architecture-roadmap"><div className="about-section-heading"><p className="about-eyebrow">HOJA DE RUTA</p><h2 id="architecture-roadmap">Crecer con criterio.</h2><p>El estado actual y las siguientes fases se distinguen de forma explícita.</p></div><div className="architecture-roadmap-grid"><article><span className="about-status">Primera versión</span><h3>Fundamentos interactivos</h3><p>Corazón, pulmones y encéfalo; piel orientativa; escena de presión arterial, RCP esquemática y guías iniciales.</p></article><article><span className="about-status about-status-muted">Siguiente fase</span><h3>Más cobertura, más revisión</h3><p>Incorporar sistemas completos y modelos con licencia documentada. Revisar contenido y anatomía con especialistas.</p></article><article><span className="about-status about-status-muted">Evolución propuesta</span><h3>Aprendizaje medible</h3><p>Escenas y rigs revisados, ejercicios, progresión y evaluación de usabilidad y rendimiento en dispositivos reales.</p></article></div></section>

        <section className="architecture-quality"><Gauge size={30} weight="light" /><div><h2>Los objetivos no son resultados medidos.</h2><p>Las metas técnicas y las ampliaciones descritas orientan el desarrollo. La primera versión tiene cobertura anatómica parcial y no dispone de validación clínica.</p></div><SiteLink href="/acerca" className="about-outline-button">Alcance y fuentes <ArrowRight size={18} /></SiteLink></section>
        <p className="architecture-reference">Modelos de referencia: <SiteLink href="https://github.com/hubmapconsortium/ccf-3d-reference-object-library" target="_blank" rel="noreferrer">Human Reference Atlas / HuBMAP <ArrowUpRight size={14} /></SiteLink> · Revisión documental: 14 de septiembre de 2026.</p>
      </div>
    </main>
  );
}
