/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ArquitecturaRouteImport } from './routes/arquitectura'
import { Route as AnatomiaRouteImport } from './routes/anatomia'
import { Route as AcercaRouteImport } from './routes/acerca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProcedimientosIndexRouteImport } from './routes/procedimientos/index'
import { Route as PrimerosAuxiliosIndexRouteImport } from './routes/primeros-auxilios/index'
import { Route as ProcedimientosSlugRouteImport } from './routes/procedimientos/$slug'
import { Route as PrimerosAuxiliosSlugRouteImport } from './routes/primeros-auxilios/$slug'

const ArquitecturaRoute = ArquitecturaRouteImport.update({
  id: '/arquitectura',
  path: '/arquitectura',
  getParentRoute: () => rootRouteImport,
} as any)
const AnatomiaRoute = AnatomiaRouteImport.update({
  id: '/anatomia',
  path: '/anatomia',
  getParentRoute: () => rootRouteImport,
} as any)
const AcercaRoute = AcercaRouteImport.update({
  id: '/acerca',
  path: '/acerca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimientosIndexRoute = ProcedimientosIndexRouteImport.update({
  id: '/procedimientos/',
  path: '/procedimientos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimerosAuxiliosIndexRoute = PrimerosAuxiliosIndexRouteImport.update({
  id: '/primeros-auxilios/',
  path: '/primeros-auxilios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimientosSlugRoute = ProcedimientosSlugRouteImport.update({
  id: '/procedimientos/$slug',
  path: '/procedimientos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimerosAuxiliosSlugRoute = PrimerosAuxiliosSlugRouteImport.update({
  id: '/primeros-auxilios/$slug',
  path: '/primeros-auxilios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/anatomia': typeof AnatomiaRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/primeros-auxilios/$slug': typeof PrimerosAuxiliosSlugRoute
  '/procedimientos/$slug': typeof ProcedimientosSlugRoute
  '/primeros-auxilios/': typeof PrimerosAuxiliosIndexRoute
  '/procedimientos/': typeof ProcedimientosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/anatomia': typeof AnatomiaRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/primeros-auxilios/$slug': typeof PrimerosAuxiliosSlugRoute
  '/procedimientos/$slug': typeof ProcedimientosSlugRoute
  '/primeros-auxilios': typeof PrimerosAuxiliosIndexRoute
  '/procedimientos': typeof ProcedimientosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/anatomia': typeof AnatomiaRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/primeros-auxilios/$slug': typeof PrimerosAuxiliosSlugRoute
  '/procedimientos/$slug': typeof ProcedimientosSlugRoute
  '/primeros-auxilios/': typeof PrimerosAuxiliosIndexRoute
  '/procedimientos/': typeof ProcedimientosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acerca'
    | '/anatomia'
    | '/arquitectura'
    | '/primeros-auxilios/$slug'
    | '/procedimientos/$slug'
    | '/primeros-auxilios/'
    | '/procedimientos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acerca'
    | '/anatomia'
    | '/arquitectura'
    | '/primeros-auxilios/$slug'
    | '/procedimientos/$slug'
    | '/primeros-auxilios'
    | '/procedimientos'
  id:
    | '__root__'
    | '/'
    | '/acerca'
    | '/anatomia'
    | '/arquitectura'
    | '/primeros-auxilios/$slug'
    | '/procedimientos/$slug'
    | '/primeros-auxilios/'
    | '/procedimientos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcercaRoute: typeof AcercaRoute
  AnatomiaRoute: typeof AnatomiaRoute
  ArquitecturaRoute: typeof ArquitecturaRoute
  PrimerosAuxiliosSlugRoute: typeof PrimerosAuxiliosSlugRoute
  ProcedimientosSlugRoute: typeof ProcedimientosSlugRoute
  PrimerosAuxiliosIndexRoute: typeof PrimerosAuxiliosIndexRoute
  ProcedimientosIndexRoute: typeof ProcedimientosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/arquitectura': {
      id: '/arquitectura'
      path: '/arquitectura'
      fullPath: '/arquitectura'
      preLoaderRoute: typeof ArquitecturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anatomia': {
      id: '/anatomia'
      path: '/anatomia'
      fullPath: '/anatomia'
      preLoaderRoute: typeof AnatomiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerca': {
      id: '/acerca'
      path: '/acerca'
      fullPath: '/acerca'
      preLoaderRoute: typeof AcercaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimientos/': {
      id: '/procedimientos/'
      path: '/procedimientos'
      fullPath: '/procedimientos/'
      preLoaderRoute: typeof ProcedimientosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeros-auxilios/': {
      id: '/primeros-auxilios/'
      path: '/primeros-auxilios'
      fullPath: '/primeros-auxilios/'
      preLoaderRoute: typeof PrimerosAuxiliosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimientos/$slug': {
      id: '/procedimientos/$slug'
      path: '/procedimientos/$slug'
      fullPath: '/procedimientos/$slug'
      preLoaderRoute: typeof ProcedimientosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeros-auxilios/$slug': {
      id: '/primeros-auxilios/$slug'
      path: '/primeros-auxilios/$slug'
      fullPath: '/primeros-auxilios/$slug'
      preLoaderRoute: typeof PrimerosAuxiliosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcercaRoute: AcercaRoute,
  AnatomiaRoute: AnatomiaRoute,
  ArquitecturaRoute: ArquitecturaRoute,
  PrimerosAuxiliosSlugRoute: PrimerosAuxiliosSlugRoute,
  ProcedimientosSlugRoute: ProcedimientosSlugRoute,
  PrimerosAuxiliosIndexRoute: PrimerosAuxiliosIndexRoute,
  ProcedimientosIndexRoute: ProcedimientosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
